import type { GlossaryEntry } from './types';

export const glossary: GlossaryEntry[] = [
  // ── Primordials ──────────────────────────────────────────────
  { english: 'Chaos', chinese: '卡俄斯', category: 'primordial', refId: 'chaos', note: 'The primeval void from which all things arose' },
  { english: 'Erebus', chinese: '厄瑞玻斯', category: 'primordial', refId: 'erebus', note: 'Personification of darkness' },
  { english: 'Eros (Primordial)', chinese: '厄洛斯', category: 'primordial', refId: 'eros-primordial', note: 'Primeval force of love and procreation' },
  { english: 'Gaia', chinese: '盖亚', category: 'primordial', refId: 'gaia', note: 'Mother Earth' },
  { english: 'Nyx', chinese: '倪克斯', category: 'primordial', refId: 'nyx', note: 'Personification of night' },
  { english: 'Ourea', chinese: '乌瑞亚', category: 'primordial', refId: 'ourea', note: 'The mountains, children of Gaia' },
  { english: 'Pontus', chinese: '蓬托斯', category: 'primordial', refId: 'pontus', note: 'Personification of the sea' },
  { english: 'Tartarus', chinese: '塔耳塔洛斯', category: 'primordial', refId: 'tartarus', note: 'The abyss beneath the Underworld' },
  { english: 'Uranus', chinese: '乌拉诺斯', category: 'primordial', refId: 'uranus', note: 'Personification of the sky' },

  // ── Titans & Titan-born ─────────────────────────────────────
  { english: 'Atlas', chinese: '阿特拉斯', category: 'titan', refId: 'atlas', note: 'Bearer of the heavens' },
  { english: 'Calypso', chinese: '卡吕普索', category: 'titan', note: 'Nymph of Ogygia, daughter of Atlas' },
  { english: 'Circe', chinese: '喀耳刻', category: 'titan', note: 'Enchantress of Aeaea, daughter of Helios' },
  { english: 'Coeus', chinese: '科俄斯', category: 'titan', refId: 'coeus' },
  { english: 'Crius', chinese: '克利俄斯', category: 'titan', refId: 'crius' },
  { english: 'Cronus', chinese: '克洛诺斯', category: 'titan', refId: 'cronus', note: 'Roman name: Saturn' },
  { english: 'Epimetheus', chinese: '厄庇墨透斯', category: 'titan', refId: 'epimetheus', note: 'Brother of Prometheus' },
  { english: 'Eos', chinese: '厄俄斯', category: 'titan', refId: 'eos', note: 'Roman name: Aurora; goddess of the dawn' },
  { english: 'Helios', chinese: '赫利俄斯', category: 'titan', refId: 'helios', note: 'Roman name: Sol; god of the sun' },
  { english: 'Hyperion', chinese: '许珀里翁', category: 'titan', refId: 'hyperion' },
  { english: 'Iapetus', chinese: '伊阿珀托斯', category: 'titan', refId: 'iapetus' },
  { english: 'Leto', chinese: '勒托', category: 'titan', refId: 'leto', note: 'Roman name: Latona; mother of Apollo and Artemis' },
  { english: 'Mnemosyne', chinese: '谟涅摩叙涅', category: 'titan', refId: 'mnemosyne', note: 'Goddess of memory, mother of the Muses' },
  { english: 'Oceanus', chinese: '俄刻阿诺斯', category: 'titan', refId: 'oceanus', note: 'The great world-encircling river' },
  { english: 'Phoebe', chinese: '福柏', category: 'titan', refId: 'phoebe' },
  { english: 'Prometheus', chinese: '普罗米修斯', category: 'titan', refId: 'prometheus', note: 'Giver of fire to mankind' },
  { english: 'Rhea', chinese: '瑞亚', category: 'titan', refId: 'rhea', note: 'Roman name: Ops; mother of the Olympians' },
  { english: 'Selene', chinese: '塞勒涅', category: 'titan', refId: 'selene', note: 'Roman name: Luna; goddess of the moon' },
  { english: 'Tethys', chinese: '忒堤斯', category: 'titan', refId: 'tethys' },
  { english: 'Theia', chinese: '忒亚', category: 'titan', refId: 'theia' },
  { english: 'Themis', chinese: '忒弥斯', category: 'titan', refId: 'themis', note: 'Goddess of law and divine order' },

  // ── Olympians & other Olympian-era deities ──────────────────
  { english: 'Aphrodite', chinese: '阿佛洛狄忒', category: 'olympian', refId: 'aphrodite', note: 'Roman name: Venus' },
  { english: 'Apollo', chinese: '阿波罗', category: 'olympian', refId: 'apollo', note: 'God of prophecy, music, and the sun' },
  { english: 'Ares', chinese: '阿瑞斯', category: 'olympian', refId: 'ares', note: 'Roman name: Mars' },
  { english: 'Artemis', chinese: '阿耳忒弥斯', category: 'olympian', refId: 'artemis', note: 'Roman name: Diana' },
  { english: 'Athena', chinese: '雅典娜', category: 'olympian', refId: 'athena', note: 'Roman name: Minerva' },
  { english: 'Demeter', chinese: '得墨忒耳', category: 'olympian', refId: 'demeter', note: 'Roman name: Ceres' },
  { english: 'Dionysus', chinese: '狄俄尼索斯', category: 'olympian', refId: 'dionysus', note: 'Roman name: Bacchus' },
  { english: 'Eris', chinese: '厄里斯', category: 'olympian', refId: 'eris', note: 'Roman name: Discordia; goddess of strife' },
  { english: 'Hades', chinese: '哈迪斯', category: 'olympian', refId: 'hades', note: 'Roman name: Pluto; lord of the Underworld' },
  { english: 'Hebe', chinese: '赫柏', category: 'olympian', refId: 'hebe', note: 'Roman name: Juventas; cupbearer of the gods' },
  { english: 'Hephaestus', chinese: '赫淮斯托斯', category: 'olympian', refId: 'hephaestus', note: 'Roman name: Vulcan' },
  { english: 'Hera', chinese: '赫拉', category: 'olympian', refId: 'hera', note: 'Roman name: Juno' },
  { english: 'Hermes', chinese: '赫尔墨斯', category: 'olympian', refId: 'hermes', note: 'Roman name: Mercury' },
  { english: 'Hestia', chinese: '赫斯提亚', category: 'olympian', refId: 'hestia', note: 'Roman name: Vesta; goddess of the hearth' },
  { english: 'Nike', chinese: '尼刻', category: 'olympian', refId: 'nike', note: 'Roman name: Victoria; goddess of victory' },
  { english: 'Persephone', chinese: '珀耳塞福涅', category: 'olympian', refId: 'persephone', note: 'Roman name: Proserpina; queen of the Underworld' },
  { english: 'Poseidon', chinese: '波塞冬', category: 'olympian', refId: 'poseidon', note: 'Roman name: Neptune' },
  { english: 'Zeus', chinese: '宙斯', category: 'olympian', refId: 'zeus', note: 'Roman name: Jupiter' },

  // ── Heroes & other key figures ──────────────────────────────
  { english: 'Achilles', chinese: '阿喀琉斯', category: 'hero', refId: 'achilles' },
  { english: 'Aeneas', chinese: '埃涅阿斯', category: 'hero', refId: 'aeneas', note: 'Trojan hero, ancestor of the Romans' },
  { english: 'Agamemnon', chinese: '阿伽门农', category: 'hero', note: 'King of Mycenae, commander at Troy' },
  { english: 'Antigone', chinese: '安提戈涅', category: 'hero', note: 'Daughter of Oedipus' },
  { english: 'Atalanta', chinese: '阿塔兰忒', category: 'hero', refId: 'atalanta' },
  { english: 'Bellerophon', chinese: '柏勒罗丰', category: 'hero', refId: 'bellerophon', note: 'Rider of Pegasus, slayer of the Chimera' },
  { english: 'Clytemnestra', chinese: '克吕泰涅斯特拉', category: 'hero', note: 'Queen of Mycenae, wife of Agamemnon' },
  { english: 'Electra', chinese: '厄勒克特拉', category: 'hero', note: 'Daughter of Agamemnon and Clytemnestra' },
  { english: 'Hector', chinese: '赫克托耳', category: 'hero', note: 'Greatest of the Trojan warriors' },
  { english: 'Helen', chinese: '海伦', category: 'hero', note: 'Helen of Troy, "the face that launched a thousand ships"' },
  { english: 'Heracles', chinese: '赫拉克勒斯', category: 'hero', refId: 'heracles', note: 'Roman name: Hercules' },
  { english: 'Iphigenia', chinese: '伊菲革涅亚', category: 'hero', note: 'Daughter of Agamemnon, sacrificed at Aulis' },
  { english: 'Jason', chinese: '伊阿宋', category: 'hero', refId: 'jason', note: 'Leader of the Argonauts' },
  { english: 'Jocasta', chinese: '伊俄卡斯忒', category: 'hero', note: 'Mother and wife of Oedipus' },
  { english: 'Medea', chinese: '美狄亚', category: 'hero', note: 'Sorceress of Colchis, wife of Jason' },
  { english: 'Menelaus', chinese: '墨涅拉俄斯', category: 'hero', note: 'King of Sparta, husband of Helen' },
  { english: 'Metis', chinese: '墨提斯', category: 'titan', refId: 'zeus', note: 'Oceanid of wise counsel, first wife of Zeus, mother of Athena; swallowed by Zeus — see his featured story' },
  { english: 'Odysseus', chinese: '奥德修斯', category: 'hero', refId: 'odysseus', note: 'Roman name: Ulysses' },
  { english: 'Oedipus', chinese: '俄狄浦斯', category: 'hero', note: 'King of Thebes, solver of the Sphinx\'s riddle' },
  { english: 'Orestes', chinese: '俄瑞斯忒斯', category: 'hero', note: 'Son of Agamemnon, avenger of his father' },
  { english: 'Orpheus', chinese: '俄耳甫斯', category: 'hero', refId: 'orpheus', note: 'The legendary musician who descended to the Underworld' },
  { english: 'Paris', chinese: '帕里斯', category: 'hero', note: 'Trojan prince who judged the beauty contest and took Helen' },
  { english: 'Patroclus', chinese: '帕特洛克罗斯', category: 'hero', note: 'Beloved companion of Achilles' },
  { english: 'Penelope', chinese: '珀涅罗珀', category: 'hero', note: 'Faithful wife of Odysseus' },
  { english: 'Perseus', chinese: '珀尔修斯', category: 'hero', refId: 'perseus', note: 'Slayer of Medusa' },
  { english: 'Priam', chinese: '普里阿摩斯', category: 'hero', note: 'Last king of Troy' },
  { english: 'Telemachus', chinese: '忒勒马科斯', category: 'hero', note: 'Son of Odysseus and Penelope' },
  { english: 'Theseus', chinese: '忒修斯', category: 'hero', refId: 'theseus', note: 'Slayer of the Minotaur, king of Athens' },

  // ── Creatures ───────────────────────────────────────────────
  { english: 'Cerberus', chinese: '刻耳柏洛斯', category: 'creature', note: 'The three-headed hound of Hades' },
  { english: 'Cyclopes', chinese: '独眼巨人', category: 'creature', note: 'One-eyed smiths who forged Zeus\'s thunderbolt: Brontes, Steropes, Arges' },
  { english: 'Hecatoncheires', chinese: '百臂巨人', category: 'creature', note: 'The Hundred-Handed Ones — Briareus, Cottus, Gyges — who won the Titanomachy for Zeus' },
  { english: 'Chelone', chinese: '刻洛涅', category: 'creature', refId: 'zeus', note: 'Nymph who mocked the wedding of Zeus and Hera and was turned into the tortoise, forever carrying her house on her back' },
  { english: 'Medusa', chinese: '美杜莎', category: 'creature', refId: 'medusa', note: 'The mortal Gorgon with serpent hair; once a priestess of Athena' },
  { english: 'Minotaur', chinese: '弥诺陶洛斯', category: 'creature', note: 'The bull-headed monster of the Labyrinth' },
  { english: 'Pegasus', chinese: '珀伽索斯', category: 'creature', note: 'The winged horse born from Medusa\'s blood; see the Medusa story' },
  { english: 'Polyphemus', chinese: '波吕斐摩斯', category: 'creature', note: 'The Cyclops blinded by Odysseus' },
  { english: 'Sphinx', chinese: '斯芬克斯', category: 'creature', note: 'The riddling monster of Thebes' },

  // ── Places ──────────────────────────────────────────────────
  { english: 'Aeaea', chinese: '埃埃亚岛', category: 'place', refId: 'aeaea', note: 'Island of Circe' },
  { english: 'Argos', chinese: '阿尔戈斯', category: 'place', refId: 'argos' },
  { english: 'Athens', chinese: '雅典', category: 'place', refId: 'athens' },
  { english: 'Aulis', chinese: '奥利斯', category: 'place', refId: 'aulis' },
  { english: 'Chryse', chinese: '克律塞', category: 'place', refId: 'chryse' },
  { english: 'Colchis', chinese: '科尔喀斯', category: 'place', refId: 'colchis' },
  { english: 'Corinth', chinese: '科林斯', category: 'place', refId: 'corinth' },
  { english: 'Crete', chinese: '克里特', category: 'place', refId: 'crete' },
  { english: 'Delphi', chinese: '德尔斐', category: 'place', refId: 'delphi' },
  { english: 'Delos', chinese: '提洛岛', category: 'place', refId: 'delos' },
  { english: 'Gates of the Underworld', chinese: '冥界之门', category: 'place', refId: 'underworld-gates' },
  { english: 'Island of Aeolus', chinese: '埃俄洛斯岛', category: 'place', refId: 'aeolus-island' },
  { english: 'Island of the Cyclopes', chinese: '独眼巨人岛', category: 'place', refId: 'cyclops-island' },
  { english: 'Ithaca', chinese: '伊萨卡', category: 'place', refId: 'ithaca' },
  { english: 'Laestrygonia', chinese: '莱斯特律戈涅斯', category: 'place', refId: 'laestrygonia', note: 'Land of the cannibal giants' },
  { english: 'Land of the Lotus-Eaters', chinese: '食莲人岛', category: 'place', refId: 'lotus-island' },
  { english: 'Lemnos', chinese: '利姆诺斯岛', category: 'place', refId: 'lemnos' },
  { english: 'Lesbos', chinese: '莱斯博斯岛', category: 'place', refId: 'lesbos' },
  { english: 'Lyrnessus', chinese: '吕耳涅索斯', category: 'place', refId: 'lyrnessus' },
  { english: 'Mount Olympus', chinese: '奥林匹斯山', category: 'place', refId: 'olympus', note: 'Dwelling of the Twelve Olympians' },
  { english: 'Mount Othrys', chinese: '俄特律斯山', category: 'place', refId: 'thessaly', note: 'Titan stronghold in the Titanomachy, at the southern edge of the Thessalian plain' },
  { english: 'Plains of Thessaly', chinese: '色萨利平原', category: 'place', refId: 'thessaly', note: 'Battlefield of the ten-year Titanomachy' },
  { english: 'Mycenae', chinese: '迈锡尼', category: 'place', refId: 'mycenae' },
  { english: 'Naxos', chinese: '纳克索斯岛', category: 'place', refId: 'naxos' },
  { english: 'Ogygia', chinese: '奥古吉埃岛', category: 'place', refId: 'ogygia', note: 'Island of Calypso' },
  { english: 'Scheria', chinese: '斯克里亚岛', category: 'place', refId: 'scheria', note: 'Island of the Phaeacians' },
  { english: 'Scylla and Charybdis', chinese: '斯库拉与卡律布狄斯', category: 'place', refId: 'scylla-charybdis' },
  { english: 'Sea of the Sirens', chinese: '塞壬海域', category: 'place', refId: 'sirens-sea' },
  { english: 'Sparta', chinese: '斯巴达', category: 'place', refId: 'sparta' },
  { english: 'Thebes', chinese: '忒拜', category: 'place', refId: 'thebes', note: '亦译"底比斯"' },
  { english: 'Thrinacia', chinese: '特里纳喀亚岛', category: 'place', refId: 'thrinacia', note: 'Island of the cattle of Helios' },
  { english: 'Troy', chinese: '特洛伊', category: 'place', refId: 'troy', note: 'Also called Ilium (伊利昂)' },
  { english: 'Underworld', chinese: '冥界', category: 'place', refId: 'underworld', note: 'Realm of Hades and Persephone' },

  // ── Stories ─────────────────────────────────────────────────
  { english: 'House of Atreus', chinese: '阿特柔斯家族', category: 'story', refId: 'house-of-atreus', note: 'The cursed house of Agamemnon and Orestes' },
  { english: 'House of Cadmus', chinese: '卡德摩斯家族', category: 'story', refId: 'house-of-cadmus' },
  { english: 'House of Thebes', chinese: '忒拜家族', category: 'story', refId: 'house-of-thebes', note: 'The saga of Oedipus and his children' },
  { english: 'Golden Fleece', chinese: '金羊毛', category: 'story', refId: 'golden-fleece', note: 'The quest of Jason and the Argonauts' },
  { english: 'Argonauts', chinese: '阿尔戈英雄', category: 'story', refId: 'golden-fleece', note: 'The heroes who sailed with Jason aboard the Argo' },
  { english: 'Iliad', chinese: '伊利亚特', category: 'story', refId: 'iliad', note: 'Epic poem of Homer' },
  { english: 'Odyssey', chinese: '奥德赛', category: 'story', refId: 'odyssey', note: 'Epic poem of Homer' },
  { english: 'Trojan War', chinese: '特洛伊战争', category: 'story', refId: 'trojan-war' },
  { english: 'Titanomachy', chinese: '提坦之战', category: 'story', refId: 'zeus', note: 'The ten-year war in which Zeus overthrew the Titans; see Zeus\'s featured story' },
  { english: 'Theft of Fire', chinese: '普罗米修斯盗火', category: 'story', refId: 'prometheus', note: 'Prometheus steals fire from heaven for mankind' },
  { english: 'Prometheus Bound', chinese: '被缚的普罗米修斯', category: 'story', refId: 'prometheus', note: 'Tragedy of Aeschylus on the chained Titan' },
  { english: 'Medusa', chinese: '美杜莎', category: 'story', refId: 'medusa', note: 'From priestess to Gorgon: the curse, the slaying, and the birth of Pegasus' },

  // ── Concepts ────────────────────────────────────────────────
  { english: 'Ambrosia', chinese: '神馐', category: 'concept', note: 'The food of the gods, granting immortality' },
  { english: 'Fates (Moirai)', chinese: '摩伊赖', category: 'concept', note: 'The three sisters who spin, measure, and cut the thread of life' },
  { english: 'Furies (Erinyes)', chinese: '厄里倪厄斯', category: 'concept', note: 'Avenging spirits of blood-guilt' },
  { english: 'Kleos', chinese: '荣耀', category: 'concept', note: 'Undying glory won through heroic deeds' },
  { english: 'Pandora', chinese: '潘多拉', category: 'concept', note: 'The first woman, whose opened jar released every sorrow into the world' },
  { english: 'Muses', chinese: '缪斯', category: 'concept', note: 'The nine goddesses of the arts and inspiration' },
  { english: 'Nectar', chinese: '仙露', category: 'concept', note: 'The drink of the gods' },
  { english: 'Xenia', chinese: '宾客之道', category: 'concept', note: 'The sacred law of hospitality between host and guest' },
];
