import type { Hero } from './types';

export const heroes: Hero[] = [
  {
    id: 'heracles',
    name: 'Heracles',
    epithet: 'the Mightiest of Heroes',
    origin: 'Thebes (born), Tiryns (raised)',
    parents: 'Zeus and the mortal Alcmene; stepson of Amphitryon',
    famousFor: 'The Twelve Labors',
    summary:
      "Heracles — Hercules to the Romans — is the greatest of Greek heroes, the strong man who made the world safe for mankind. Hated by Hera from the cradle for his father's infidelity, he was driven by her into a madness in which he slew his own wife and children; in atonement he served his cowardly kinsman Eurystheus and performed the Twelve Labors. His life was one long toil: he wrestled giants, sacked Troy, marched briefly with the Argonauts, and freed the chained Prometheus. He died in agony from the centaur Nessus's poisoned blood, given in innocence by his wife Deianira. Yet his story alone among the heroes ends in triumph: the pyre on Mount Oeta burned away his mortality, and Zeus raised him to Olympus, where he wed Hebe and made his peace with Hera.",
    keyMyths: [
      'The Twelve Labors: the Nemean lion, the Lernaean hydra, the Ceryneian hind, the Erymanthian boar, the Augean stables, the Stymphalian birds, the Cretan bull, the mares of Diomedes, the girdle of Hippolyta, the cattle of Geryon, the apples of the Hesperides, and Cerberus dragged up from the underworld.',
      'Maddened by Hera, he killed his wife Megara and their children; the Labors were his penance.',
      'He freed Prometheus from his chains and slew the eagle that fed on his liver.',
      'He wrestled Death himself to win back Alcestis for her husband Admetus.',
      'Dying from Nessus\'s blood, he ascended from the pyre to Olympus and married Hebe.',
    ],
    relatedIds: ['zeus', 'hera', 'athena', 'hermes', 'hades', 'hebe', 'prometheus', 'jason', 'atlas'],
    locationIds: ['thebes', 'argos', 'mycenae', 'olympus', 'underworld', 'caucasus'],
  },
  {
    id: 'perseus',
    name: 'Perseus',
    epithet: 'the Gorgon-Slayer',
    origin: 'Argos',
    parents: 'Zeus and Danaë, daughter of King Acrisius',
    famousFor: 'Slaying Medusa and rescuing Andromeda',
    summary:
      "Perseus was conceived when Zeus came to the imprisoned Danaë in a shower of gold, for an oracle had warned her father Acrisius that her son would kill him. Cast to sea in a chest with his mother, the boy grew up on Seriphos, where King Polydectes sent him on an impossible quest: the head of the Gorgon Medusa, whose gaze turned men to stone. Armed by Athena with a mirrored shield, by Hermes with a sword, and with Hades's cap of invisibility, winged sandals, and a kibisis for the head, he slew the Gorgon as she slept. Flying home on the newborn Pegasus's winds, he turned the sea-monster to stone and saved the chained princess Andromeda, whom he wed. Back on Seriphos he turned Polydectes and his court to stone; later, in Larissa, a discus he threw struck and killed Acrisius — the oracle fulfilled. He founded Mycenae, and through his line came Heracles.",
    keyMyths: [
      'Born to Danaë after Zeus visited her brazen tower as a shower of gold, he was cast into the sea in a chest.',
      'Guided by the Graeae, three crones sharing one eye, he found and beheaded Medusa, using his shield as a mirror.',
      'From Medusa\'s neck sprang the winged horse Pegasus and the giant Chrysaor.',
      'He rescued Andromeda from the sea-monster and made her his wife.',
      'His discus killed his grandfather Acrisius by chance, fulfilling the oracle he had fled.',
    ],
    relatedIds: ['zeus', 'athena', 'hermes', 'hades', 'heracles', 'medusa'],
    locationIds: ['argos', 'mycenae'],
  },
  {
    id: 'theseus',
    name: 'Theseus',
    epithet: 'Slayer of the Minotaur',
    origin: 'Athens (born at Troezen)',
    parents: 'King Aegeus of Athens and Aethra; Poseidon was also named his father',
    famousFor: 'Killing the Minotaur in the Labyrinth and uniting Attica',
    summary:
      "Theseus is the national hero of Athens, its unifier and lawgiver. His story begins with a cryptic oracle at Delphi that sent King Aegeus to Troezen, where the wise King Pittheus gave him his daughter Aethra; some say Poseidon also claimed the child that same night, giving Theseus a double paternity — mortal king and sea god. Before departing, Aegeus hid his sword and sandals beneath a great stone, charging Aethra to send their son to Athens when he could lift it. Raised at Troezen, the boy proved fearless — when young Heracles visited and set down his lion-skin, the other children fled, but Theseus seized an axe and ran at it. At sixteen he lifted the stone, claimed his father's tokens, and walked the dangerous road to Athens, clearing it of bandits by giving each the death he dealt. His greatest deed was to sail to Crete among the tribute of youths, thread the Labyrinth with Ariadne's clew of thread, and slay the Minotaur. Returning, he forgot to hoist the white sail; Aegeus, seeing black, cast himself into the sea that bears his name. As king he joined the villages of Attica into one city, but his later years darkened: the rape of Helen, the descent to the underworld with Pirithous, and exile to Skyros, where he was pushed from a cliff.",
    keyMyths: [
      'Born after a cryptic oracle sent Aegeus to Troezen, where Pittheus gave him Aethra; Poseidon was also named his father. Aegeus hid sword and sandals beneath a stone for their son to lift when he came of age.',
      'On the road to Athens he killed the bandits Periphetes, Sinis the pine-bender, the Crommyonian sow, Sciron, and Procrustes — each by his own device.',
      'He slew the Minotaur in the Labyrinth, escaping by Ariadne\'s thread.',
      'He forgot the white sail, and his father Aegeus leapt to his death into the Aegean.',
      'He united the towns of Attica into a single Athenian state.',
      'With Pirithous he descended to the underworld to seize Persephone, and was rescued by Heracles.',
    ],
    relatedIds: ['poseidon', 'heracles', 'hades', 'dionysus', 'atalanta', 'house-of-atreus'],
    locationIds: ['athens', 'crete', 'naxos', 'underworld'],
  },
  {
    id: 'achilles',
    name: 'Achilles',
    epithet: 'the Swift-Footed',
    origin: 'Phthia, Thessaly',
    parents: 'Peleus and the sea-goddess Thetis',
    famousFor: 'The greatest Greek warrior of the Trojan War; the wrath of the Iliad',
    summary:
      "Achilles, son of the mortal Peleus and the goddess Thetis, was given the choice of a long obscure life or a short one crowned with undying glory — and chose glory. Reared by the centaur Chiron, he was the swiftest and deadliest of the Greeks at Troy. When Agamemnon took his prize Briseis, Achilles withdrew in wrath, and the war nearly failed; only the death of his beloved Patroclus, killed by Hector in Achilles' own armor, drew him back. In a fury of grief he slaughtered the Trojans, slew Hector before the walls, and dragged the body behind his chariot until old Priam's tears moved him to pity. Soon after, Paris's arrow, guided by Apollo, struck him down; later tradition made the heel his one vulnerable spot. His armor, given to Odysseus rather than Ajax, caused Ajax's madness and death.",
    keyMyths: [
      'Thetis dipped him in the Styx to make him invulnerable — later tradition says all but the heel she held.',
      'His quarrel with Agamemnon over Briseis opens the Iliad and sets its tragedy in motion.',
      'Patroclus died wearing his armor; Achilles returned to battle and killed Hector.',
      'Reconciled to grief, he returned Hector\'s body to Priam, the Iliad\'s most human scene.',
      'He was killed by Paris\'s arrow, guided by Apollo; his arms went to Odysseus, driving Ajax to madness.',
    ],
    relatedIds: ['odysseus', 'apollo', 'zeus', 'athena', 'hephaestus', 'eris', 'iliad', 'trojan-war'],
    locationIds: ['troy'],
  },
  {
    id: 'odysseus',
    name: 'Odysseus',
    epithet: 'the Man of Many Wiles',
    origin: 'Ithaca',
    parents: 'Laertes and Anticleia',
    famousFor: 'The Wooden Horse and the ten-year wanderings of the Odyssey',
    summary:
      "Odysseus, king of Ithaca, is the cleverest of the Greeks — the 'man of twists and turns.' He feigned madness to dodge the call to Troy, but once there became the war's great strategist and devised the Wooden Horse that took the city. His homecoming lasted ten more years: the Lotus-Eaters, the Cyclops Polyphemus whom he blinded, Circe who turned his crew to swine, a descent to consult the dead, the Sirens, Scylla and Charybdis, and the slaughter of the Sun-god's cattle that cost him every companion. Seven years he lay with the nymph Calypso before the gods let him sail. He reached Ithaca disguised as a beggar, strung his great bow, slew the suitors who plagued his house, and was at last known to Penelope, his patient and matching-minded wife.",
    keyMyths: [
      'He devised the Wooden Horse, the stratagem that ended the Trojan War.',
      'He blinded the Cyclops Polyphemus after giving his name as "Nobody," earning Poseidon\'s undying wrath.',
      'Circe, the Sirens, and Scylla and Charybdis thinned his crew; on Thrinacia the last were lost.',
      'He descended alive to the underworld to hear the prophet Teiresias.',
      'Disguised as a beggar, he strung his bow, slew the suitors, and reclaimed Ithaca and Penelope.',
    ],
    relatedIds: ['athena', 'poseidon', 'hermes', 'achilles', 'iliad', 'odyssey', 'trojan-war'],
    locationIds: ['ithaca', 'troy', 'aeaea'],
  },
  {
    id: 'jason',
    name: 'Jason',
    epithet: 'Captain of the Argo',
    origin: 'Iolcus, Thessaly',
    parents: 'Aeson, rightful king of Iolcus, and his queen (Alcimede in some tellings)',
    famousFor: 'Leading the Argonauts to win the Golden Fleece',
    summary:
      "Jason was the rightful heir of Iolcus, sent away to be raised by the centaur Chiron while the usurper Pelias held the throne. He returned wearing one sandal — the very sign an oracle had warned Pelias to fear — and was sent to fetch the Golden Fleece from Colchis at the edge of the world. With Hera's favor he gathered the greatest heroes of the age aboard the Argo: Heracles, Orpheus, the twins Castor and Pollux, and many more. Past the Clashing Rocks they came to Colchis, where the king's daughter Medea, smitten by Hera's design, gave him the magic to yoke fire-breathing bulls, sow dragon's teeth, and drug the sleepless serpent. They fled with the Fleece, but Jason's later betrayal of Medea for a Corinthian princess brought ruin: she killed his bride and their own children, and the broken hero died years later when the rotting Argo's prow fell on his head.",
    keyMyths: [
      'He came to Iolcus with one sandal, fulfilling the oracle that terrified Pelias.',
      'The Argo carried the flower of Greek heroes past the Symplegades, the Clashing Rocks.',
      'With Medea\'s sorcery he yoked the fire-breathing bulls, defeated the crop of armed men, and stole the Fleece.',
      'Medea tricked Pelias\'s daughters into cutting their father to pieces; the pair were exiled to Corinth.',
      'His betrayal of Medea ended in the murder of his bride and sons — Euripides\' darkest tragedy.',
    ],
    relatedIds: ['golden-fleece', 'hera', 'athena', 'heracles', 'orpheus', 'atalanta'],
    locationIds: ['colchis', 'corinth', 'lemnos'],
  },
  {
    id: 'atalanta',
    name: 'Atalanta',
    epithet: 'the Fleet-Footed Huntress',
    origin: 'Arcadia (Boeotia in some tellings)',
    parents: 'Iasus, who exposed her for being born a girl (Schoeneus in the Boeotian version)',
    famousFor: 'The Calydonian Boar hunt and the footrace of the golden apples',
    summary:
      "Atalanta was exposed on a mountainside by a father who wanted a son, suckled by a bear, and raised by hunters into the fastest runner and fiercest huntress in Greece. Devoted to Artemis, she took a vow of maidenhood and slew the centaurs who tried to force her. At the Calydonian Boar hunt she struck the beast first, and Meleager's award of the hide to her set off the feud that destroyed his house. To escape marriage she set a contest: any suitor must outrun her or die. Hippomenes won by guile — Aphrodite gave him three golden apples, and Atalanta, stopping to gather them, lost the race. Apollodorus ends their tale with the pair transformed into lions for profaning a shrine of Zeus.",
    keyMyths: [
      'Exposed at birth and suckled by a she-bear, she grew up a virgin huntress of Artemis.',
      'She drew first blood in the Calydonian Boar hunt, receiving the hide from Meleager.',
      'She wrestled Peleus at the funeral games of Pelias — and won.',
      'Hippomenes beat her in the fatal footrace by dropping Aphrodite\'s three golden apples.',
      'For defiling a sacred grove, the lovers were transformed into lions.',
    ],
    relatedIds: ['artemis', 'aphrodite', 'jason'],
    locationIds: [],
  },
  {
    id: 'bellerophon',
    name: 'Bellerophon',
    epithet: 'Rider of Pegasus',
    origin: 'Corinth (born), Lycia (exile)',
    parents: 'Glaucus and Eurynome; some say Poseidon',
    famousFor: 'Slaying the Chimera astride the winged horse Pegasus',
    summary:
      "Bellerophon, having killed a man in Corinth, fled to the court of Proetus of Argos, whose queen falsely accused him when he refused her love. Proetus sent him to Lycia bearing a sealed letter that asked its reader, King Iobates, to kill the bearer. Unwilling to slay a guest, Iobates set him lethal labors instead, chief among them the Chimera — a fire-breathing monster part lion, part goat, part serpent. Athena gave Bellerophon the golden bridle with which he mastered Pegasus, and from the winged horse's back he shot the monster down. He defeated the Solymi and the Amazons, and destroyed the ambush Iobates set for him, until the king gave him his daughter and half his kingdom. But pride undid him: he tried to fly Pegasus up to Olympus itself, was thrown, and wandered the Aleian plain alone, shunned by all, until he died.",
    keyMyths: [
      'Falsely accused by Queen Anteia, he carried the letter that ordered his own death.',
      'With Athena\'s golden bridle he tamed Pegasus at the spring of Peirene.',
      'From the air he slew the Chimera, then defeated the Solymi and the Amazons.',
      'He survived Iobates\' ambush and won the king\'s daughter and half the kingdom.',
      'Attempting to fly to Olympus, he was thrown from Pegasus and ended his days a wretched wanderer.',
    ],
    relatedIds: ['athena', 'poseidon', 'zeus'],
    locationIds: ['corinth', 'argos'],
  },
  {
    id: 'orpheus',
    name: 'Orpheus',
    epithet: 'the Thracian Singer',
    origin: 'Thrace',
    parents: 'Apollo (or the Thracian king Oeagrus) and the Muse Calliope',
    famousFor: 'Descending alive into the Underworld to win back Eurydice',
    summary:
      "Orpheus, son of the Muse Calliope, played the lyre so sweetly that trees and rocks followed him and wild beasts lay down to listen. He sailed with the Argonauts, where his song alone outsang the Sirens and saved the ship. When his bride Eurydice died of a snakebite on their wedding day, he dared the descent no living man makes: his music charmed Cerberus, halted the torments of the damned, and moved even Hades and Persephone to tears. They granted that Eurydice might follow him up — if he did not look back until both stood in the light. At the very threshold he turned, and she was lost a second time. Grieving, he shunned all women, and the Maenads of Thrace tore him apart; his head, still singing, floated down the Hebrus and came to rest on Lesbos.",
    keyMyths: [
      'His song charmed stones, trees, and beasts, and outsang the Sirens on the Argonauts\' voyage.',
      'He descended alive to the underworld and softened the hearts of Hades and Persephone.',
      'At the gates of the upper world he looked back, and Eurydice vanished forever.',
      'Thracian Maenads, scorned in his grief, tore him limb from limb.',
      'His severed head floated, still singing, to the shores of Lesbos.',
    ],
    relatedIds: ['apollo', 'hermes', 'hades', 'persephone', 'jason', 'dionysus'],
    locationIds: ['underworld', 'lesbos'],
    features: [
      {
        eyebrow: 'The Descent for Love',
        title: 'Orpheus and Eurydice',
        lede: 'When his bride fell to a serpent’s fang, the singer did what no living man dares: he walked down into the house of the dead to ask for her back. His lyre won what strength never could — and a single glance undid it all.',
        facts: [
          { label: 'His bride', value: 'Eurydice, a Dryad' },
          { label: 'Her death', value: 'A serpent’s bite' },
          { label: 'His guide below', value: 'Hermes, at Zeus’s word' },
          { label: 'The guard dog', value: 'Cerberus, three-headed' },
          { label: 'The condition', value: 'Do not look back' },
          { label: 'His killers', value: 'The Maenads of Thrace' },
          { label: 'His memorial', value: 'The constellation Lyra' },
          { label: 'Sung by', value: 'Virgil and Ovid' },
        ],
        sections: [
          {
            heading: 'The Wedding and the Snake',
            body: 'Orpheus, son of the Muse Calliope, loved the Dryad Eurydice, and their wedding day was blessed — or so it seemed. The omens darkened at once: the torches smoked and would not catch, and Hymen, god of marriage, brought no joy with him. The end came swift and senseless. The new bride was walking the meadow with her sister nymphs — Virgil adds that the beekeeper Aristaeus saw her, burned with desire, and gave chase — when her foot came down upon a serpent in the deep grass, and its fangs found her ankle. Eurydice died on her wedding day, and her shade went down to the house of Hades. Orpheus mourned her above the earth until mourning was not enough.',
          },
          {
            heading: 'The Descent No Living Man Makes',
            body: 'He resolved on the unthinkable: to go down alive and win her back. First he carried his grief upward — some tellings say he came before Zeus himself and sang his loss on Olympus, and the Father, moved but unwilling to break the law of his own realm, told him that this suit lay below, in the kingdom of his brother. And Hermes, the guide of souls who walks both worlds, pitied the singer and showed him the road down — past the black cave at Taenarum, down the road the ghosts go, where the light thins and the air grows cold. Orpheus went, carrying nothing but his lyre.',
          },
          {
            heading: 'Charming the Watchers of the Dead',
            body: 'Every terror of that road he disarmed with song. Charon, the gaunt ferryman who takes no passenger without a coin and no living passenger at all, heard the lyre and poled him across the Styx in silence. And at the gate of the underworld rose Cerberus, the three-headed hound of Hades, his triple throats baying — until the first chord fell, and the monster’s ears drooped, and the great snake-maned body sank down meek as a housedog and let the singer pass. Beyond him stretched the fields of the dead, and still the music walked before Orpheus like a lamp.',
          },
          {
            heading: 'The Song That Stopped Hell',
            body: 'Then Orpheus stood before the dark throne and sang his plea to Hades and Persephone: love brought me here; we are all owed to you in the end; let her go back and live out her allotted years, and she will be yours again soon enough. And hell itself stopped to listen. Tantalus forgot his thirst and ceased grasping at the fleeing water; Ixion’s wheel stood still; Sisyphus sat down upon his stone; the Danaids set down their sieves; and the Furies, who have no pity, wept — Ovid says their iron cheeks were wet with tears. The king and queen of the dead looked at one another, and Hades spoke: she may follow you. One condition only binds the gift — you must not turn your eyes upon her until both of you stand in the upper light. Look back, and she is lost.',
          },
          {
            heading: 'The Threshold',
            body: 'So they climbed the steep, dark, muffled road, he first and she behind — forbidden to speak, forbidden to look. The way was long, and the silence behind him was unbearable: was she there? Was he leading a shadow of a shadow? They were almost at the edge, the grey light of the world already on his face, when love conquered the god’s command — Orpheus turned. In that instant Eurydice slipped backward, stretching out her arms, her lips shaping a last farewell he could scarcely hear, and was gone a second time — dying, the poets say, her second death, with no complaint but that she was loved too much. Orpheus flung himself after her, but Charon now refused him the crossing. Seven days he sat on the bank of the Styx, fasting and weeping, and then crept back alone into the sunlight, which he could no longer bear.',
          },
          {
            heading: 'The Maenads',
            body: 'For three years Orpheus wandered the Thracian hills, singing only of his loss, and turned his heart against all women. The Thracian women — the Maenads, the Bacchantes, wild with the worship of Dionysus — burned at his scorn. They found him singing on a hillside and fell on him with stones and uprooted trees and farm tools. But the first volley fell harmless at his feet, charmed mid-flight by his song; so the Maenads raised their own music — drums, and shrill flutes, and the howling of the god — and drowned his lyre in noise. Then the weapons no longer listened, and the frenzied band seized the singer and tore him limb from limb, scattering the pieces across the fields. His lyre gave one last grieving note, and the rocks wept, and the trees shed their leaves for him.',
          },
          {
            heading: 'The Lyre Among the Stars',
            body: 'His head and his lyre were thrown into the river Hebrus, and marvelously they floated — the head still singing Eurydice’s name, the lyre still murmuring — down to the sea and across to the shores of Lesbos, the island that ever after was first in song. The Muses, his mother Calliope at their head, gathered the fragments of their son and buried them at Leibethra beneath Olympus, where the nightingales sing sweeter over his grave than anywhere on earth. And so that the singer would never be lost, the Muses begged one last gift from Zeus: the Father took up Orpheus’s lyre and set it in the heavens as the constellation Lyra — the Lyre — where it still shines on summer nights, the instrument of the man whose music moved death itself, burning quietly above the world he sang to.',
          },
        ],
      },
    ],
  },
  {
    id: 'aeneas',
    name: 'Aeneas',
    epithet: 'the Dutiful',
    origin: 'Troy (born on Mount Ida)',
    parents: 'The goddess Aphrodite and the mortal Anchises',
    famousFor: 'Escaping the sack of Troy and founding the line of Rome',
    summary:
      "Aeneas, son of Aphrodite and the Trojan prince Anchises, was the gods' chosen survivor of Troy. In the Iliad he fights among the foremost Trojans and is twice rescued by divine hands — Apollo lifts him from Diomedes' assault, and even Poseidon, Troy's enemy, saves him from Achilles, for destiny wills that his line shall outlive the city. When Troy fell, he carried his aged father on his shoulders and led his young son through the flames, an image of pious duty. The later Roman tradition, above all Virgil's Aeneid, sent him wandering west — to Carthage and the tragic love of Queen Dido — before he reached Italy, where his descendants founded Rome. Among the heroes he is unique: a figure in whom Greek myth hands its legacy to Rome.",
    keyMyths: [
      'Poseidon himself saved him from Achilles, declaring his line destined to survive Troy.',
      'He bore his father Anchises on his shoulders out of the burning city.',
      'In Virgil\'s telling he abandoned Queen Dido of Carthage at the gods\' command; she died on her pyre.',
      'He reached Italy, where his line gave birth to Romulus and Rome.',
    ],
    relatedIds: ['aphrodite', 'apollo', 'poseidon', 'achilles', 'trojan-war', 'iliad'],
    locationIds: ['troy'],
  },
];
