import type { God } from './types';

export const olympians: God[] = [
  {
    id: 'zeus',
    name: 'Zeus',
    epithet: 'the Cloud-Gatherer',
    title: 'King of the Gods, God of Sky and Thunder',
    generation: 'olympian',
    romanName: 'Jupiter',
    domain: ['sky', 'thunder', 'justice', 'kingship', 'oaths'],
    symbols: ['thunderbolt', 'eagle', 'oak', 'scepter', 'aegis'],
    parents: 'Cronus and Rhea',
    consort: 'Hera (and many goddesses and mortal women)',
    children: 'Athena, Apollo, Artemis, Ares, Hephaestus, Hermes, Dionysus, Persephone, Heracles, Perseus, the Muses',
    summary:
      "Zeus is the youngest child of Cronus and Rhea, saved from being swallowed by his father and raised in secret on Crete. He led the gods in the Titanomachy, the ten-year war that overthrew the Titans, and thereafter ruled from Olympus as king of gods and men. His weapon is the thunderbolt, forged by the Cyclopes, and his will upholds the order of the cosmos. Homer calls him father of gods and men, the guardian of oaths, guests, and suppliants. Yet he is also a restless lover whose many unions with goddesses and mortals populate the mythic world with heroes. In the Iliad he holds the scales of fate over the battlefield of Troy, bowing even to what destiny decrees.",
    keyMyths: [
      'Hidden at birth on Crete, he overthrew Cronus and freed his swallowed siblings.',
      'He led the gods to victory over the Titans in the Titanomachy and cast them into Tartarus.',
      'He survived the rebellion of the monster Typhon, last challenger to his rule.',
      'He divided the world by lot with his brothers, taking the sky while Poseidon took the sea and Hades the underworld.',
      'In the Iliad he weighs the fates of Greeks and Trojans and honors his promise to Thetis.',
      'Warned that his first wife Metis would bear a son mightier than himself, he swallowed her — and Athena sprang fully armed from his head.',
    ],
    relatedIds: ['cronus', 'rhea', 'hera', 'poseidon', 'hades', 'athena', 'apollo', 'heracles', 'prometheus', 'iliad', 'trojan-war'],
    locationIds: ['olympus', 'crete', 'delphi', 'thessaly'],
    features: [
      {
      eyebrow: 'The War That Made a King',
      title: 'The Titanomachy',
      lede: 'For ten years the old gods and the new tore at one another across the plains of Thessaly — until Zeus, with weapons forged in the deep and giants at his side, cast the Titans down and founded the order of Olympus.',
      facts: [
        { label: 'Battlefield', value: 'The plains of Thessaly' },
        { label: 'Duration', value: 'Ten years' },
        { label: 'Titan general', value: 'Atlas, son of Iapetus' },
        { label: 'Titan stronghold', value: 'Mount Othrys' },
        { label: 'Olympian stronghold', value: 'Mount Olympus' },
        { label: 'Decisive allies', value: 'The Cyclopes and the Hecatoncheires' },
        { label: 'Outcome', value: 'Titans chained in Tartarus' },
        { label: "Atlas's fate", value: 'To bear the heavens forever' },
      ],
      sections: [
        {
          heading: 'The Gathering of Two Hosts',
          body: 'When Zeus came of age, he returned from Crete and, with the help of the wise Metis, slipped Cronus a potion that forced the old king to disgorge the children he had swallowed — Hestia, Demeter, Hera, Hades, and Poseidon. United at last, the six siblings declared war on their father. The Titans rallied on Mount Othrys, the rugged peak of southern Thessaly where Cronus held his throne; their foremost champion and field commander was Atlas, son of Iapetus, strongest of the Titan-born. Against them, Zeus raised his standard on Mount Olympus to the north. Between the two mountain camps stretched the broad plains of Thessaly, and there, on that level ground, the two hosts of gods collided.',
        },
        {
          heading: 'Ten Years of Stalemate',
          body: 'The war ground on for ten full years without decision. The Titans were ancient, vast, and seasoned; the young Olympians, for all their courage, could not break them. Day after day the earth shook with the shock of their battles, yet neither host yielded. At last Gaia, the Earth herself, revealed to Zeus the path to victory: hidden away in the depths of Tartarus lay allies more powerful than any army — the very ones Uranus and Cronus in their fear had chained beneath the world. If Zeus dared to free them, the war could be won.',
        },
        {
          heading: 'The Cyclopes Forge the Weapons',
          body: 'Zeus descended into Tartarus, slew the she-dragon Campe who guarded the prisoners, and broke the chains of the Cyclopes — Brontes, Steropes, and Arges, the one-eyed master smiths, sons of Uranus and Gaia. In gratitude the three brothers took up their hammers and forged the arms that would decide the war: for Zeus the thunder and the blazing thunderbolt, for Poseidon the earth-shaking trident, and for Hades the cap of darkness that makes its wearer unseen. Armed in the deep, the three elder brothers rose to the battlefield wielding powers no Titan could match.',
        },
        {
          heading: 'The Hundred-Handed Ones Join the Fray',
          body: "Nor did Zeus stop there. He freed also the Hecatoncheires — Briareus, Cottus, and Gyges, the Hundred-Handed Ones, each with fifty heads and a hundred arms — whom Cronus had likewise bound in the abyss. Revived with nectar and ambrosia, they agreed to fight for Olympus, and Briareus would later be honored with marriage to Poseidon's daughter. In the final battle the three giants stood on the Olympian line, and from their three hundred hands they hurled a storm of boulders so dense it darkened the sky, battering the Titans where they stood.",
        },
        {
          heading: 'The Fall of the Titans',
          body: 'Then Zeus himself unloosed the full fury of his lightning. Flame wrapped the earth, the forests blazed, the land and even the streams of Ocean seethed, and a burning heat seized the whole world as though earth and sky were crashing together. Beneath that thunder and that rain of stone the Titans broke. The Olympians seized them, bound them in chains, and hurled them into Tartarus — as far beneath the earth, says Hesiod, as the earth is beneath the sky. There Poseidon set gates of bronze upon the abyss, and the Hecatoncheires took up their post as its everlasting wardens.',
        },
        {
          heading: "Atlas Bears the Heavens",
          body: 'Not every Titan shared the same sentence. Atlas, who had led the Titan host as its general, was singled out for a heavier doom than Tartarus. Zeus condemned him to stand at the far western edge of the world, before the house of Night, and to hold the broad heavens upon his head and tireless hands forever. In later art the sky he carries is rendered as a celestial globe — which is why, to this day, a book of maps bears his name. Others fared better: Oceanus had stayed neutral and kept his stream; Themis and Prometheus had sided with Zeus; and Styx, first of all to join the Olympians with her children, was honored forever as the river by which the gods swear their unbreakable oaths.',
        },
        {
          heading: 'A New Order of the World',
          body: "With the Titans chained, the three sons of Cronus divided the cosmos by lot: Zeus took the sky and was acknowledged king of gods and men, Poseidon the sea, and Hades the realm of the dead, while the earth and high Olympus remained common to all. So ended the age of the Titans and began the reign of Olympus. Yet the old king was not without a gentler afterlife: in later telling, Zeus relented and released Cronus to rule the Isles of the Blessed, where the spirits of heroes dwell in an age like the golden one over which the Titan had once presided.",
        },
      ],
      },
      {
        eyebrow: 'The Wife He Swallowed',
        title: 'Zeus and Metis',
        lede: 'Before Hera, there was Metis — the wisest being in the cosmos, and Zeus’s first wife. When fate warned that her unborn son would overthrow him, the new king of the gods answered not with thunder but with his father’s own weapon: he swallowed her whole.',
        facts: [
          { label: 'The bride', value: 'Metis, an Oceanid' },
          { label: 'Her parents', value: 'Oceanus and Tethys' },
          { label: 'Her name means', value: 'Wise counsel, cunning' },
          { label: 'Hesiod’s praise', value: 'Wisest of gods and mortals' },
          { label: 'The prophecy', value: 'A son mightier than his father' },
          { label: 'Zeus’s answer', value: 'He swallowed her by guile' },
          { label: 'Born of his head', value: 'Athena, fully armed' },
          { label: 'Metis’s fate', value: 'His inner counselor forever' },
        ],
        sections: [
          {
            heading: 'The Wisest of All',
            body: 'Metis was a daughter of Oceanus and Tethys, one of the three thousand Oceanids — but among them all she stood apart. Her very name means “counsel” and “cunning craft,” and Hesiod calls her the most knowing of gods and mortal men. It was Metis who had given Zeus the potion that forced Cronus to disgorge his swallowed children; without her stratagem the war against the Titans might never have begun. Grateful, enamored, and shrewd enough to want wisdom on his own side, Zeus took her as his first wife.',
          },
          {
            heading: 'The Prophecy of a Mightier Son',
            body: 'But Earth and Sky — Gaia and Uranus, who had watched two dynasties fall — warned Zeus of what was fated. Metis was destined to bear two children: first a daughter who would be her father’s equal in strength and wise counsel, and then a son of overbearing heart who would become king of gods and men. It was the old curse of the cosmos repeating itself: Uranus had been overthrown by his son Cronus, and Cronus by his son Zeus. Now the same shadow reached for Zeus.',
          },
          {
            heading: 'Swallowed by Cunning',
            body: 'Zeus did not raise the thunderbolt against her. He did what his father and grandfather had done before him — he devoured — but he did it with a subtlety they had never possessed. Coaxing Metis with honeyed words, he deceived her into his power and swallowed her whole; in some tellings she had been shifting her shape to escape him, and he caught her in her smallest form. So the goddess of cunning was taken in by cunning, and the cycle of sons devouring fathers was broken by a husband devouring his wife.',
          },
          {
            heading: 'The Birth of Athena',
            body: 'In time Zeus was seized by a raging pain in his skull, a pounding worse than any thunderclap. By the waters of the river Triton, Hephaestus — or, some say, Prometheus — split the god’s head open with a bronze axe, and out sprang Athena, fully grown and fully armed, in gleaming helmet and spear, her war-cry shaking heaven and earth while the sun stood still to look. The daughter of the prophecy had come — wise as her mother, mighty as her father — but the foretold son was never born at all.',
          },
          {
            heading: 'The Counselor Within',
            body: 'Metis did not die. She dwells still within Zeus, says the Theogony, where she sits devising for him both good and ill — wisdom become a part of the king himself. And therein lies the point of the tale: Cronus swallowed his children and so earned their hatred, but Zeus swallowed counsel and made it his own. His rule, unlike his father’s, would be guided from within by metis. Athena, born of his head alone, became the dearest of his children, bearer of his aegis and his thunderbolt — the living proof that the wisest of the gods had chosen a wiser path than Cronus.',
          },
        ],
      },
      {
        eyebrow: 'The Stormy Marriage of Heaven',
        title: 'Zeus and Hera',
        lede: 'He wooed her as a shivering cuckoo in the rain; their wedding night, the poets say, lasted three hundred years. Yet the marriage of heaven’s king and queen is the stormiest in all myth — a union of golden apples, borrowed girdles, and thunderous quarrels.',
        facts: [
          { label: 'The bride', value: 'Hera, his sister' },
          { label: 'Her parents', value: 'Cronus and Rhea' },
          { label: 'His disguise', value: 'A cuckoo drenched in rain' },
          { label: 'Gaia’s gift', value: 'The golden apple-tree' },
          { label: 'Wedding night', value: 'Three hundred years' },
          { label: 'Sacred places', value: 'Argos and Samos' },
          { label: 'Their children', value: 'Ares, Hephaestus, Hebe, Eileithyia' },
          { label: 'Their union', value: 'The sacred marriage (hieros gamos)' },
        ],
        sections: [
          {
            heading: 'The Cuckoo in the Storm',
            body: 'Hera, proud and watchful, at first refused her brother’s suit. So Zeus laid aside his majesty and turned himself into a bedraggled cuckoo, shivering and drenched in a winter storm he himself had summoned. Seeing the pitiful bird outside her window, Hera took it to her breast to warm it — whereupon Zeus resumed his true form and pressed his claim upon her. To veil her shame, or because love had at last been kindled, she consented to be his wife. That is why, to this day, the cuckoo perches atop Hera’s scepter in her temple images.',
          },
          {
            heading: 'The Wedding of Heaven',
            body: 'Their wedding was the greatest feast the young cosmos had seen. All creation brought gifts, and grandmother Gaia gave the richest of all: a tree bearing apples of pure gold, which was planted in a garden at the western edge of the world, tended by the Hesperides and guarded by the hundred-headed dragon Ladon. Only one creature scorned the feast: the nymph Chelone, who mocked the wedding and refused to leave her house. For her contempt, Hermes hurled the house into the river and turned her into the tortoise — her name means just that in Greek — doomed to carry her home upon her back forever and, in some tellings, to keep her impudent tongue eternally still. As for the wedding night, the old scholiasts say it lasted three hundred years on the island of Samos — the island that ever after held Hera’s greatest sanctuary.',
          },
          {
            heading: 'Queen at His Side',
            body: 'Hera was never a mere consort. Of all the Olympians she alone is Zeus’s lawful wife, sharing his throne and his royal dignity; in the Iliad she is honored as the greatest of the goddesses. Because she is goddess of marriage itself, their union is the hieros gamos — the sacred marriage of which every mortal wedding is an echo. At Argos and Samos her cult was older than Zeus’s own, and poets never let him forget that the queen of heaven has a pride equal to the king’s.',
          },
          {
            heading: 'Quarrels and Deceptions',
            body: 'Yet no house in heaven is stormier. Hera rages at Zeus’s endless infidelities and hunts his lovers and their children without mercy; Zeus answers with thunderous threats, reminding her how he once hung her from the sky with golden chains about her wrists and anvils at her feet. Their most famous duel of wits comes in the Iliad: forbidden to aid the Greeks, Hera bathes, anoints herself, borrows Aphrodite’s enchanted girdle, and seduces Zeus on the heights of Mount Ida so that Sleep can close his eyes — while Poseidon, un-watched, turns the battle. The episode is called the Deception of Zeus, and it is the queen’s finest hour.',
          },
          {
            heading: 'The One Rebellion',
            body: 'Once it went further than quarrels. In the Iliad’s own telling, Hera conspired with Poseidon and Athena to bind Zeus in chains and take back Olympus. The plot failed before a blow was struck: the sea-nymph Thetis, ever loyal to Zeus, summoned the hundred-handed Briareus up to Olympus, and at the sight of that giant seated beside the king, the conspirators lost their nerve and scattered. It was the only time the gods moved against Zeus — and significantly, not even his wife could carry Olympus with her.',
          },
          {
            heading: 'A Marriage That Endures',
            body: 'For all the storms, the marriage holds. Zeus and Hera cannot be faithful to peace, but neither can they part; their quarrels are simply the weather of Olympus, rolling thunder followed by clear sky. The poets always end where they began: the king and queen seated side by side on one throne, the dispute settled or merely postponed, the sacred marriage of heaven enduring — as enduring, and as tempestuous, as the sky itself.',
          },
        ],
      },
    ],
  },
  {
    id: 'hera',
    name: 'Hera',
    epithet: 'the Ox-Eyed Queen',
    title: 'Queen of the Gods, Goddess of Marriage and Women',
    generation: 'olympian',
    romanName: 'Juno',
    domain: ['marriage', 'women', 'childbirth', 'kingship'],
    symbols: ['peacock', 'cow', 'diadem', 'pomegranate', 'cuckoo'],
    parents: 'Cronus and Rhea',
    consort: 'Zeus',
    children: 'Ares, Hephaestus, Hebe, Eileithyia',
    summary:
      "Hera, daughter of Cronus and Rhea, is both sister and wife of Zeus and queen of the Olympian court. She presides over marriage and the life of women, and her sacred rites at Argos and Samos were among the oldest in Greece. Myth remembers her above all for her jealousy: she pursues Zeus's lovers and their children with unrelenting anger, none more famously than Heracles. In the Trojan War she sides fiercely with the Greeks, humiliating herself even to seduce and deceive her own husband to turn the tide of battle. Dignified, proud, and formidable, she is the divine image of the wronged but unbowed queen.",
    keyMyths: [
      'She persecuted Heracles all his life, sending serpents to his cradle and madness upon his house.',
      'Spurned in the Judgment of Paris, she became an implacable enemy of Troy.',
      'In the Iliad she borrows Aphrodite\'s girdle to beguile Zeus and aid the Greeks.',
      'She transformed the princess Io into a cow and set hundred-eyed Argos to guard her.',
      'Her sacred animal, the peacock, bears the eyes of Argos on its tail.',
    ],
    relatedIds: ['zeus', 'cronus', 'rhea', 'ares', 'hephaestus', 'hebe', 'heracles', 'iliad', 'trojan-war', 'house-of-atreus'],
    locationIds: ['olympus', 'argos'],
  },
  {
    id: 'poseidon',
    name: 'Poseidon',
    epithet: 'the Earth-Shaker',
    title: 'God of the Sea, Earthquakes, and Horses',
    generation: 'olympian',
    romanName: 'Neptune',
    domain: ['sea', 'earthquakes', 'horses', 'storms'],
    symbols: ['trident', 'horse', 'dolphin', 'bull'],
    parents: 'Cronus and Rhea',
    consort: 'Amphitrite',
    children: 'Triton, Polyphemus, Pegasus (by Medusa), Theseus (in some traditions)',
    summary:
      "Poseidon, brother of Zeus and Hades, drew the sea as his realm when the world was divided by lot. With a strike of his trident he raises tempests, splits rocks, and shakes the earth, earning his Homeric title Earth-Shaker. He is a proud and quarrelsome god: he contested Athena for the patronage of Athens and lost, and he never forgave Odysseus for blinding his son, the Cyclops Polyphemus. Sailors and coastal cities honored him with sacrifices of bulls and horses, creatures he was said to have created. Beneath the waves he keeps a golden palace, yet he sits with the Twelve on Olympus.",
    keyMyths: [
      'He won his queen, the Nereid Amphitrite, after she fled his suit — a dolphin found her in hiding, pleaded his cause, and was rewarded with a place among the stars.',
      'He contested Athena for Athens, offering a salt spring where she offered the olive tree.',
      'His wrath pursued Odysseus for ten years after the blinding of Polyphemus.',
      'With Apollo he built the walls of Troy, then sent a sea-monster when King Laomedon refused payment.',
      'He fathered the winged horse Pegasus upon the Gorgon Medusa.',
      'He created the first horse, and horsemen everywhere claimed his patronage.',
    ],
    relatedIds: ['zeus', 'hades', 'athena', 'odysseus', 'theseus', 'odyssey', 'iliad', 'trojan-war'],
    locationIds: ['olympus', 'corinth', 'troy', 'naxos'],
    features: [
      {
      eyebrow: 'The Wooing of the Sea Queen',
      title: 'Poseidon and Amphitrite',
      lede: 'Even the Earth-Shaker could not command love. When the Nereid Amphitrite fled his suit to the farthest edge of the world, it was not the trident but a dolphin’s gentle tongue that won her — and Poseidon, grateful, set his matchmaker among the stars.',
      facts: [
        { label: 'The bride', value: 'Amphitrite, a Nereid' },
        { label: 'Her father', value: 'Nereus, the Old Man of the Sea' },
        { label: 'Where he first saw her', value: 'Dancing on Naxos' },
        { label: 'Her refuge', value: 'Beyond Ocean, near Atlas' },
        { label: 'The matchmaker', value: 'Delphin the dolphin' },
        { label: 'His reward', value: 'The constellation Delphinus' },
        { label: 'Their palace', value: 'Golden halls beneath the sea' },
        { label: 'Their children', value: 'Triton, Rhode, Benthesicyme' },
      ],
      sections: [
        {
          heading: 'The Dance on Naxos',
          body: 'Among the fifty daughters of Nereus, the truthful Old Man of the Sea, and the Oceanid Doris, none moved more gracefully than Amphitrite. One day, as the Nereids danced on the shores of Naxos, their feet keeping time with the rhythm of the waves, Poseidon rose from his waters and saw her. The sight struck the god of the sea like his own trident strikes the rock: at once he desired her, not as a passing fancy, but as his queen — the one who would sit beside him in his golden palace beneath the Aegean and share his rule over all the waters of the world.',
        },
        {
          heading: 'The Flight of the Nereid',
          body: 'But Amphitrite would not have him. Perhaps she feared the tempests of his famous temper, or wished to keep the free, untethered life of a sea-maiden, unwed and answerable to no one. Whatever her reason, she fled the moment his suit was pressed — away from the bright shallows of the Cyclades, out past the pillars of the known world, to the western edge of Ocean where the great Titan Atlas stands bearing the weight of the heavens. There, in that twilight at the rim of the earth, she hid herself, certain that even a god would never find her.',
        },
        {
          heading: "The Dolphin's Embassy",
          body: 'Poseidon searched the seas in vain, then sent out envoys to comb the deep for his lost bride. Among them swam Delphin, the dolphin, wisest and most eloquent of the creatures of the sea. It was Delphin who at last discovered Amphitrite in her hiding place at the ends of Ocean. He did not seize her or summon the god; instead he spoke to her gently and long, pleading Poseidon’s cause — praising the honor of wedding the ruler of the seas, the splendor of his court, and the depth of a love that had driven the Earth-Shaker to search the whole wide ocean for her. Word by patient word, the dolphin’s persuasion melted her resolve, and Amphitrite consented to return and be wed.',
        },
        {
          heading: 'The Wedding and the Gift of Stars',
          body: 'So Amphitrite came back across the sea, and the wedding of Poseidon was celebrated in his golden halls beneath the waves, with all the powers of the deep in attendance. The god did not forget who had won him his queen: in gratitude he caught up Delphin and set his image in the night sky, where the small constellation Delphinus — the Dolphin — still swims among the stars, a memorial of the embassy that moved a goddess. It was a rare gentleness from the most turbulent of gods, and the poets remembered it.',
        },
        {
          heading: 'Queen of the Sea',
          body: 'From that day Amphitrite reigned beside Poseidon as queen of the sea. She bore him Triton, the merman herald who blows his twisted conch to calm or rouse the waves, and the daughters Rhode and Benthesicyme. In the art of later ages she rides at her husband’s side in his chariot of hippocampi, robed and crowned, attended by Nereids and Tritons — no longer the fleeing maiden of Naxos, but the calm and stately mistress of the deep, the one voice that could soften the Earth-Shaker’s wrath when storms rose.',
        },
      ],
      },
    ],
  },
  {
    id: 'demeter',
    name: 'Demeter',
    epithet: 'Lady of the Golden Grain',
    title: 'Goddess of Agriculture, Grain, and the Harvest',
    generation: 'olympian',
    romanName: 'Ceres',
    domain: ['agriculture', 'grain', 'harvest', 'fertility of the earth'],
    symbols: ['wheat sheaf', 'torch', 'cornucopia', 'poppy'],
    parents: 'Cronus and Rhea',
    children: 'Persephone (by Zeus)',
    summary:
      "Demeter, sister of Zeus, gives mortals the gift of grain and the arts of cultivation; her name was invoked at every sowing and harvest. Her defining myth is the loss of her daughter Persephone, seized by Hades while gathering flowers. In grief Demeter wandered the earth disguised as an old woman, and the fields went barren beneath her sorrow. Zeus was forced to compromise: Persephone would spend part of each year with her mother and part below, and so the seasons turn. At Eleusis she founded the Mysteries, secret rites that promised initiates a better lot after death.",
    keyMyths: [
      'She searched nine days with torches for Persephone, learning the truth from Helios.',
      'Her mourning brought famine on the earth until Zeus yielded.',
      'At Eleusis she taught her Mysteries, the most revered rites of the Greek world.',
      'She nursed the infant Demophon in fire, seeking to make him immortal, until his mother cried out in fear.',
    ],
    relatedIds: ['persephone', 'hades', 'zeus', 'hestia', 'cronus', 'rhea'],
    locationIds: ['olympus'],
  },
  {
    id: 'athena',
    name: 'Athena',
    epithet: 'the Grey-Eyed',
    title: 'Goddess of Wisdom, Strategic Warfare, and Crafts',
    generation: 'olympian',
    romanName: 'Minerva',
    domain: ['wisdom', 'strategic warfare', 'crafts', 'weaving', 'civic order'],
    symbols: ['owl', 'olive tree', 'aegis', 'helmet', 'Gorgoneion'],
    parents: 'Zeus alone — born from his head after he swallowed the Titaness Metis',
    summary:
      "Athena sprang fully armed from the head of Zeus, her battle-cry shaking heaven and earth. She is the patron of wise counsel and disciplined war, the opposite of her brutal brother Ares, and the protector of cities — above all Athens, which took her name after she won its patronage with the gift of the olive. A virgin goddess, she mothers no children but champions heroes: she armed Perseus, steadied Heracles, and never abandoned Odysseus through his long wandering. Her owl sees in the dark, her aegis bears the Gorgon's head, and her loom and craft rival her spear. On Olympus her judgment is trusted even by Zeus.",
    keyMyths: [
      'She leapt from the head of Zeus in full armor after he swallowed Metis.',
      'She defeated Poseidon in the contest for Athens by giving the city the olive tree.',
      'She guided and disguised Odysseus across the whole of the Odyssey.',
      'She gave Perseus the mirrored shield and Bellerophon the golden bridle.',
      'She turned the boastful weaver Arachne into a spider.',
    ],
    relatedIds: ['zeus', 'ares', 'poseidon', 'odysseus', 'perseus', 'heracles', 'bellerophon', 'odyssey', 'iliad', 'trojan-war'],
    locationIds: ['athens', 'olympus'],
    features: [
      {
        eyebrow: 'The Olive and the Salt Spring',
        title: 'The Contest for Attica',
        lede: 'In the days of earth-born King Cecrops, two of the greatest Olympians claimed the same city. Zeus would not judge between his brother and his daughter — so the people of Athens voted, and the city’s women decided it by a single vote. They have been paying for that vote, the old story says, ever since.',
        facts: [
          { label: 'The king', value: 'Cecrops, earth-born' },
          { label: 'The prize', value: 'Patronage of Attica' },
          { label: 'Poseidon’s gift', value: 'The salt spring' },
          { label: 'Athena’s gift', value: 'The olive tree' },
          { label: 'The arbiter', value: 'Zeus — who abstained' },
          { label: 'Decided by', value: 'One vote — the women’s' },
          { label: 'The penalty', value: 'Athenian women lost the vote' },
          { label: 'The temple', value: 'The Erechtheion, for both' },
        ],
        sections: [
          {
            heading: 'Cecrops, the Earth-Born King',
            body: 'Before Athens was Athens, the land of Attica was ruled by Cecrops, its first king — a strange, double-formed creature, man above and serpent below, sprung from the soil itself. It was Cecrops who gathered the scattered country folk into a single city on the rock of the Acropolis, then called Cecropia after himself; who first taught them marriage, the burial of the dead, and the writing of letters; who first offered sacrifice to Zeus without blood. Under his long and peaceable reign the city grew rich enough to be worth coveting — and coveted it was, by two of the twelve Olympians at once.',
          },
          {
            heading: 'Two Gods Claim One City',
            body: 'Poseidon, lord of the sea, and Athena, the grey-eyed daughter of Zeus, both desired the city for their own, and the quarrel nearly came to open blows. Zeus himself was named arbiter — and promptly declined the honor. He would not offend his brother by siding with his daughter, nor his daughter by siding with his brother, and so he abstained, throwing the judgment upon others: the contest would be decided by gifts. Each god would give the city the best thing in their power, and the more useful gift would win. Some say Cecrops and the elders judged; others that the twelve gods sat as witnesses, with Cecrops testifying to what he had seen. All agree on what happened next.',
          },
          {
            heading: 'The Trident and the Olive',
            body: 'Poseidon went first. He reared up in all his majesty and struck the bare rock of the Acropolis with his trident, and where the blow fell a spring burst forth — salt water, a little sea in the heart of the citadel, the wonder of the harbor-god (some versions say it was the horse he made there, the first ever seen). The people marveled. Then Athena knelt and set into the rock a small grey-green sapling: the first olive tree, which would give food and oil, wood and light, shade and trade — the wealth of Attica for all generations to come. When the wonder faded, usefulness spoke louder than spectacle. The olive was judged the greater gift.',
          },
          {
            heading: 'Decided by a Single Vote',
            body: 'Here the Roman antiquarian Varro, cited by Augustine in the City of God, preserves the strangest version of the verdict. Since Zeus would not decide, the question was put to the citizens themselves — and in those first days, the women of Athens still held the vote. The men of the city voted for Poseidon; the women voted for Athena; and the women outnumbered the men by exactly one. By that single vote the goddess won her city, and the city took her name: Athens. The marks of the contest were kept as sacred relics ever after — Poseidon’s salt well and Athena’s olive tree both stood on the Acropolis, side by side, for a thousand years.',
          },
          {
            heading: 'The Wrath of the Sea',
            body: 'Poseidon did not take the loss quietly. In his rage he flooded the Thriasian plain below the city, the flat land toward Eleusis, drowning fields and farms beneath the salt water — the sea-god’s answer to losing to a sapling. The terrified Athenians sought to appease him, and the settlement they struck, says the old account, fell upon the very women whose votes had won the day. Three penalties were laid on them: the women of Athens would never vote again; children would no longer bear their mother’s name, but their father’s; and the women themselves would no longer be called Athenians. So, the myth explains, the democracy of Athens became a city of men — a memory, in story form, of a time when women had held power and lost it.',
          },
          {
            heading: 'Two Temples on One Rock',
            body: 'And yet the sea-god was not cast out. To crown their reconciliation, the Athenians built on the Acropolis a temple shared by both rivals: the Erechtheion, where Athena Polias, guardian of the city, kept her ancient olive-wood image in the eastern chamber — and where, in the western hall, altars stood to Poseidon-Erechtheus, for the great king Erechtheus was worshipped in the sea-god’s name. Beneath its porch ran the marks themselves: the salt well that splashed when the south wind blew, and the living olive tree. When the Persians burned the Acropolis in 480 BCE and the olive was charred, the Athenians swore it put out a new green shoot the very next day. Athena kept the city and her greater temple — the Parthenon, raised to her as Parthenos, the Maiden — but Poseidon kept his altar in her house, his trident-mark beside her tree. The contest ended, as few Olympian quarrels do, in a shared hearth.',
          },
        ],
      },
    ],
  },
  {
    id: 'apollo',
    name: 'Apollo',
    epithet: 'the Far-Shooter',
    title: 'God of Prophecy, Music, Archery, and Healing',
    generation: 'olympian',
    romanName: 'Apollo',
    domain: ['prophecy', 'music', 'archery', 'healing and plague', 'the sun', 'poetry'],
    symbols: ['lyre', 'laurel', 'bow and silver arrows', 'raven', 'tripod'],
    parents: 'Zeus and Leto',
    consort: 'None — his loves (Daphne, Hyacinthus, Coronis) end tragically',
    children: 'Asclepius, Orpheus (in some traditions)',
    summary:
      "Apollo, twin of Artemis, was born on the island of Delos after his mother Leto wandered the earth seeking a place Hera's jealousy would permit. He is the most Greek of gods: lord of the lyre and the bow, of prophecy and purification, of the plague-arrows that open the Iliad and the healing arts that cure them. At Delphi he slew the serpent Python and founded the oracle where his priestess spoke the god's will to all Greece. Beautiful, young, and terrible, he demands measure and self-knowledge — yet his own loves, from Daphne to Hyacinthus, end in loss. Later ages identified him with the sun itself.",
    keyMyths: [
      'Born on Delos, he walked at once and claimed the lyre and bow as his own.',
      'He slew the Python at Delphi and established its famous oracle.',
      'His arrows brought plague on the Greek camp when Agamemnon dishonored his priest Chryses.',
      'He guided the arrow of Paris that struck down Achilles.',
      'Daphne fled his love and became the laurel, his sacred tree.',
    ],
    relatedIds: ['artemis', 'leto', 'zeus', 'hermes', 'achilles', 'orpheus', 'iliad', 'trojan-war'],
    locationIds: ['delphi', 'delos', 'olympus'],
    features: [
      {
        eyebrow: 'The Founding of Delphi',
        title: 'Apollo and the Serpent Python',
        lede: 'Four days out of his mother’s womb, the Far-Shooter climbed Mount Parnassus with his bow, and there, beside the sacred spring, he slew the dragon that had plagued the land — and on the spot where its body rotted, he founded the most famous oracle of the ancient world.',
        facts: [
          { label: 'The monster', value: 'Python, a she-dragon' },
          { label: 'Her lair', value: 'A spring beneath Parnassus' },
          { label: 'Sent by', value: 'Hera, against Leto (some say)' },
          { label: 'Apollo’s age', value: 'Four days old' },
          { label: 'The weapon', value: 'His unerring arrows' },
          { label: 'The name', value: 'Pytho — “the place of rotting”' },
          { label: 'The oracle', value: 'Delphi, seat of the Pythia' },
          { label: 'The first priests', value: 'Cretan sailors, led by a dolphin' },
        ],
        sections: [
          {
            heading: 'The Serpent of the Spring',
            body: 'Beneath the twin cliffs of Mount Parnassus, where the Castalian spring runs cold and clear, there lay in those days a monster: Python, a huge she-dragon, bloated and deadly, who haunted the wooded ravines and the holy spring. Some said she was the ancient guardian of a far older seat of prophecy there — an oracle of Mother Earth herself — and would let no mortal approach it. Others, and the poet Hyginus among them, tell that Hera bore her or sent her for one purpose: to hunt Leto across the world while she carried Zeus’s twins, so that the goddess of childbirth found no rest even after Delos received her. Either way, the dragon had made the place a terror: flocks were savaged, farmers killed, and no traveler dared the road past her spring.',
          },
          {
            heading: 'Four Days Old',
            body: 'Apollo did not wait to grow. Born on Delos beneath the palm tree, he was fed on nectar and ambrosia, burst his swaddling bands at once, and made the first declaration of his divine career: the lyre shall be mine, and the curved bow, and I shall declare to mankind the unerring counsel of Zeus. Then he walked — the Homeric Hymn delights in it — the newborn god striding across the islands while the goddesses marveled. He was four days old when he came to the slopes of Parnassus seeking the oracle Earth’s serpent had closed, and he carried the silver bow his father’s smiths had made for a god of archery.',
          },
          {
            heading: '“Rot There Upon the Earth”',
            body: 'The meeting was at the spring. Python reared up, vast and hissing, and Apollo drew and loosed — arrow after arrow, the Hymn says, a thousand shafts from his unerring string, until the monster lay wallowing in her own black blood, gasping out her life in terrible, rending breaths. The god stood over the carcass and spoke the vaunting words that named the place forever: rot there now, upon the fruitful earth — pytheu, in Greek — no longer a blight upon men who bring their offerings here. And so the dragon rotted away under the sun, and the spot was called Pytho, and Apollo himself took the epithet Pythian. The people of the country round, delivered, cried out in joy and gave the god a new byname of healing and deliverance.',
          },
          {
            heading: 'The Founding of the Oracle',
            body: 'A god, even a young one, may not shed even monstrous blood without rite: some tellings send Apollo into exile and purification — to the Vale of Tempe, where he was cleansed with laurel — before he could take up the seat of prophecy, and Delphi itself reenacted the slaying and the exile in its great Septeria festival for centuries after. But the oracle was his. The Pythian seat had passed down an elder line — Gaia first, then Themis, then Phoebe, Apollo’s own grandmother, who yielded it to him as a birthday gift, says the prologue of Aeschylus’s Eumenides. At Delphi Apollo set his tripod, and upon it sat his priestess, the Pythia, who breathed the vapor of the holy place and spoke the god’s answers in verse. On the temple were carved the maxims that governed Greek wisdom: Know Thyself, and Nothing in Excess. For a thousand years kings and commoners, Croesus and Socrates alike, would climb the Sacred Way to hear the voice of Pythian Apollo.',
          },
          {
            heading: 'The Dolphin Priests',
            body: 'A shrine needs servants, and the Hymn tells how Apollo found them. Watching from Olympus, he saw a ship of Cretan merchants from Knossos sailing the wine-dark sea off Pylos, bound on no errand of his — and he leaped into the waves in the shape of a dolphin, huge and gleaming, and hurled himself aboard. None could loose him; the crew sat frozen while the ship, steered by no hand, ran before the wind around the Peloponnese and into the Gulf of Corinth, until it grounded at Crisa, the port below Delphi. There Apollo revealed himself in a blaze of glory, led the trembling Cretans up to his sanctuary, and made them its first priests and keepers — and that, the Greeks said, is why the holy town is called Delphi, for delphis, the dolphin. To crown it all, Apollo established the Pythian Games, held in honor of his victory over the serpent, where victors were crowned with the laurel of Tempe. So from one dragon’s death came the god’s greatest glory on earth: Delphi, the navel of the world, where all Greece came to ask its questions — and where the priestess still spoke in the name of the Far-Shooter who had climbed Parnassus at four days old.',
          },
        ],
      },
    ],
  },
  {
    id: 'artemis',
    name: 'Artemis',
    epithet: 'Lady of the Hunt',
    title: 'Goddess of the Hunt, the Wilderness, and the Moon',
    generation: 'olympian',
    romanName: 'Diana',
    domain: ['the hunt', 'wilderness', 'wild animals', 'maidens', 'childbirth', 'the moon'],
    symbols: ['bow and arrows', 'deer', 'crescent moon', 'cypress', 'hunting hounds'],
    parents: 'Zeus and Leto',
    children: 'None — she is an eternal maiden',
    summary:
      "Artemis, twin sister of Apollo, was born on Delos and, in the telling of the poets, helped deliver her own brother the same day. She claimed from Zeus the gifts of eternal maidenhood, a silver bow, and the mountains as her domain. She ranges the wild with her nymphs and hounds, swift to punish any who offend her purity or her mother. Yet she is also the gentle protector of young creatures, of girls on the threshold of marriage, and of women in labor. Like Apollo she was later joined to a light of heaven — the moon.",
    keyMyths: [
      'She demanded and won from Zeus eternal maidenhood and rule over the mountains.',
      'She turned Actaeon into a stag for spying on her bath, and his own hounds tore him apart.',
      'She halted the winds at Aulis, demanding Iphigenia before the fleet could sail for Troy.',
      'With Apollo she slew the children of Niobe, who had mocked their mother Leto.',
      'Orion, the giant huntsman and her companion, died by her arrows or a scorpion — the tales differ.',
    ],
    relatedIds: ['apollo', 'leto', 'zeus', 'atalanta', 'iliad', 'trojan-war', 'house-of-atreus'],
    locationIds: ['delos', 'olympus', 'crete'],
  },
  {
    id: 'ares',
    name: 'Ares',
    epithet: 'the Bane of Mortals',
    title: 'God of War and Battle-Lust',
    generation: 'olympian',
    romanName: 'Mars',
    domain: ['war', 'battle', 'violence', 'courage'],
    symbols: ['spear', 'helmet', 'shield', 'vulture', 'dog'],
    parents: 'Zeus and Hera',
    consort: 'Aphrodite (lover)',
    children: 'Deimos and Phobos (Terror and Rout), Harmonia, Eros (in some accounts)',
    summary:
      "Ares, son of Zeus and Hera, is war stripped of glory: the shrieking lust of battle, blood, and rout. Homer makes even his own father call him the most hateful of the gods. For all his fury he is often worsted — wounded by the mortal Diomedes with Athena's help, trapped in a bronze jar by the Aloadae, and netted in adultery by Hephaestus. Yet the Greeks also honored the courage he gives, and Thebes revered him as an ancestor through his daughter Harmonia. His sons Deimos and Phobos ride with him into every battle.",
    keyMyths: [
      'He fought for Troy in the Iliad and was wounded by Diomedes under Athena\'s guidance.',
      'Hephaestus trapped him in bed with Aphrodite in a net of unbreakable chains.',
      'The giant brothers Otus and Ephialtes imprisoned him in a bronze jar for thirteen months.',
      'He slew Poseidon\'s son Halirrhothius and was tried by the gods on the Areopagus in Athens.',
      'The Amazons and the dragon of Thebes\' sacred spring were called his offspring.',
    ],
    relatedIds: ['zeus', 'hera', 'aphrodite', 'hephaestus', 'athena', 'iliad', 'trojan-war', 'house-of-cadmus'],
    locationIds: ['olympus', 'athens', 'thebes'],
  },
  {
    id: 'aphrodite',
    name: 'Aphrodite',
    epithet: 'the Laughter-Loving',
    title: 'Goddess of Love, Beauty, and Desire',
    generation: 'olympian',
    romanName: 'Venus',
    domain: ['love', 'beauty', 'desire', 'procreation'],
    symbols: ['dove', 'rose', 'myrtle', 'swan', 'magic girdle'],
    parents: 'Born from the sea-foam around the severed member of Uranus (Hesiod); Homer makes her daughter of Zeus and Dione',
    consort: 'Hephaestus (husband); Ares (lover)',
    children: 'Eros, Harmonia, Deimos, Phobos, Aeneas (by the mortal Anchises)',
    summary:
      "Aphrodite rose from the sea-foam near Cyprus, stepping ashore where the grass sprang beneath her feet — so Hesiod sings, though Homer calls her daughter of Zeus. Her power bends gods and mortals alike; only Athena, Artemis, and Hestia escape it. Wed to the lame smith Hephaestus, she loves the war-god Ares, and their capture in her husband's net is Olympus's favorite scandal. To Paris she offered the fairest woman on earth, and so lit the fire of the Trojan War. She is tender and terrible at once, the force the Greeks knew no creature can refuse.",
    keyMyths: [
      'She emerged from the sea-foam and was carried ashore at Cyprus.',
      'She won the golden apple of the Judgment of Paris by promising him Helen, kindling the Trojan War.',
      'Hephaestus caught her with Ares in an invisible net and displayed them to the laughing gods.',
      'She loved the mortal Anchises and bore him Aeneas, destined to escape Troy.',
      'She gave Hippomenes three golden apples to outrun Atalanta in the fatal footrace.',
    ],
    relatedIds: ['hephaestus', 'ares', 'zeus', 'hera', 'athena', 'eris', 'atalanta', 'aeneas', 'trojan-war', 'iliad'],
    locationIds: ['olympus', 'troy'],
    features: [
      {
        eyebrow: 'Born of Blood and Foam',
        title: 'The Sea-Foam Birth',
        lede: 'When Cronus cut down his father Uranus with the adamant sickle and flung the severed member into the sea, the waves gathered white foam around it — and out of that foam, Hesiod says, stepped the most beautiful of the gods.',
        facts: [
          { label: 'Told by', value: 'Hesiod, Theogony' },
          { label: 'The weapon', value: 'Cronus’s adamant sickle' },
          { label: 'Her name means', value: 'Born of aphros — foam' },
          { label: 'Carried past', value: 'Cythera' },
          { label: 'She came ashore at', value: 'Paphos, on Cyprus' },
          { label: 'Her first attendants', value: 'Eros and Himeros' },
          { label: 'Who clothed her', value: 'The Seasons (Horai)' },
          { label: 'Her bynames', value: 'Cypris and Cytherea' },
        ],
        sections: [
          {
            heading: 'The Sickle of Cronus',
            body: 'It began with the oldest crime of the cosmos. Uranus, the starry Sky, hated his own children by Gaia and thrust them back into the Earth’s depths as fast as they were born. Gaia, groaning under the burden, made a sickle of grey adamant and begged her sons for help; only Cronus dared. When next the Sky descended upon the Earth in love, Cronus reached out from his hiding place, seized his father, and cut off his manhood with the jagged blade — then flung it behind him into the deep sea. From the blood that fell on Earth sprang the Erinyes, the Giants, and the ash-tree nymphs. But the member itself drifted long upon the waves.',
          },
          {
            heading: 'Foam on the Wide Sea',
            body: 'Around the severed flesh the sea gathered a white foam — aphros, in Greek — and within the foam a maiden grew. The current carried her first past holy Cythera, and then to wave-washed Cyprus, and there she stepped ashore at Paphos. Where her feet touched the land, grass and flowers sprang up beneath them. Because she rose from the foam she is called Aphrodite; because she passed Cythera, Cytherea; because Cyprus received her, the Cypris — Cyprus remained her holiest island forever after, and Paphos the seat of her greatest sanctuary.',
          },
          {
            heading: 'Clothed by the Seasons',
            body: 'The Homeric Hymn tells how she came to the gods. The West Wind bore her gently to shore upon the soft-foaming waves, and there the gold-crowned Seasons — the Horai, keepers of heaven’s gates — received her gladly. They clothed her in immortal garments, set a golden crown upon her head and flowers of copper and precious gold in her pierced ears, hung golden necklaces about her soft neck, and adorned her as they adorn themselves when they go to the dance of the gods. Then they led her to the immortals, who marveled and greeted her, and every god desired to take her home as his wife. Eros — Love — and fair Himeros — Desire — walked beside her from the first and have never left her since.',
          },
          {
            heading: 'A Goddess Older Than Olympus',
            body: 'It is worth pausing on what this birth means. Zeus is her father only in Homer’s gentler version, where she is the daughter of Zeus and Dione. In Hesiod’s older telling she is no one’s daughter and no one’s child: she is older than Zeus, older than most of Olympus, born of the primal violence between Sky and Earth — which is why her power bends nearly every god, not merely mortals. Only three goddesses escape her: Athena, Artemis, and Hestia, the virgins she cannot touch. The Greeks who pictured her rising from the waves understood exactly what they were saying: desire is not a domestic virtue invented by civilization. It is one of the oldest things in the world.',
          },
        ],
      },
      {
        eyebrow: 'Love and War',
        title: 'Aphrodite and Ares',
        lede: 'Wed to the lame smith of the gods, the goddess of love chose the one Olympian who was everything her husband was not: beautiful, violent, and reckless. Their affair was Olympus’s favorite scandal — and from it were born Fear, Terror, and, strangest of all, Harmony.',
        facts: [
          { label: 'Her husband', value: 'Hephaestus the smith' },
          { label: 'Her lover', value: 'Ares, god of war' },
          { label: 'The informer', value: 'Helius, the all-seeing Sun' },
          { label: 'The trap', value: 'An invisible net' },
          { label: 'Their sons', value: 'Phobos and Deimos' },
          { label: 'Their daughter', value: 'Harmonia' },
          { label: 'Also theirs', value: 'Eros, in later telling' },
          { label: 'Sung in', value: 'Odyssey, Book 8' },
        ],
        sections: [
          {
            heading: 'A Mismatched Marriage',
            body: 'Aphrodite’s marriage to Hephaestus was a transaction, not a love match — the price the smith demanded for freeing Hera from the golden throne. The goddess of beauty found herself bound to the one god who sweated over a forge, while her own nature pulled her elsewhere: to Ares, the magnificent, bloody-handed god of war, everything her husband was not. Whenever Hephaestus was away at his beloved Lemnos, Ares came to the smith’s fine house, and the two lay together in the craftsman’s own bed — while Ares, they say, posted his attendant Alectryon at the door to warn them of the dawn. One morning the youth fell asleep, the Sun rose and saw everything, and Aphrodite in her rage turned the unlucky sentinel into the rooster, who still crows before dawn, forever warning against the Sun.',
          },
          {
            heading: 'The All-Seeing Informer',
            body: 'Helius, the Sun, from whom nothing on earth is hidden, carried the word straight to Hephaestus. The smith said nothing. He went to his forge, and in cold silence hammered out his answer: a net of chains so fine it could not be seen, so cunningly woven it could not be broken, light as the threads of a spider. He hung it about the bedposts of his own marriage bed like a canopy, announced a journey to Lemnos — and waited. Ares came before the god’s shadow had left the street, and took Aphrodite laughing to bed. The net fell.',
          },
          {
            heading: 'Held Fast Before the Gods',
            body: 'The tale of what followed — Hephaestus calling the gods to gape at the naked pair, the unquenchable laughter of heaven, Hermes declaring he would take three times the chains to lie by golden Aphrodite — is sung on this site in the tale of the smith. For Aphrodite the shame was public and total. Poseidon’s surety won her freedom; Ares fled at once to his raw north country of Thrace, and the goddess went to Cyprus, to Paphos, where the Graces bathed her and anointed her with immortal oil and dressed her in lovely garments. Then, being Aphrodite, she went on exactly as before. That is the thing the laughter of the gods concealed: she is the one Olympian who cannot be shamed out of her nature, because her nature is the force that shames everyone else.',
          },
          {
            heading: 'The Children of Love and War',
            body: 'The union of Love and War was fruitful, and its offspring are a whole philosophy. Their sons are Phobos and Deimos — Fear and Terror — the grim twins who ride beside their father’s chariot into battle, driving routs and panics before them; the Greeks painted them on the shield of Agamemnon. But their daughter is Harmonia — Harmony — the child of the two most opposite powers in heaven, as though to say that love and strife, joined, somehow produce concord. Harmonia was given in marriage to Cadmus, founder of Thebes, at the one wedding on earth the gods themselves attended — yet her bridal gift, the fatal necklace forged by the cuckolded Hephaestus, carried misery into the house of Cadmus for generations. In later tradition the Romans added that Eros himself — Cupid — was the son of Aphrodite and Ares, though the oldest poets made him a power older than either. Love and War: the Greeks saw that the two are never far apart, and gave them one household.',
          },
        ],
      },
    ],
  },
  {
    id: 'hephaestus',
    name: 'Hephaestus',
    epithet: 'the Renowned Smith',
    title: 'God of Fire, the Forge, and Craftsmanship',
    generation: 'olympian',
    romanName: 'Vulcan',
    domain: ['fire', 'the forge', 'metalworking', 'craftsmanship', 'volcanoes'],
    symbols: ['hammer', 'anvil', 'tongs', 'forge', 'donkey'],
    parents: 'Hera alone (Hesiod); Zeus and Hera (Homer)',
    consort: 'Aphrodite',
    children: 'None of note in the mainstream myths',
    summary:
      "Hephaestus is the lame smith of the gods, hurled from Olympus at birth — by Hera, ashamed of his crooked legs, or by Zeus in anger; Homer preserves both tellings. He landed on Lemnos, which became his sacred island and the site of his forge beneath the volcano. From his workshop come the marvels of myth: the thunderbolt of Zeus, the armor of Achilles, the necklace of Harmonia, and Pandora, the first woman. Wedded to Aphrodite, he is wronged but never mocked with impunity: his cunning net once held the goddess and Ares fast for all Olympus to see. The Iliad ends its great shield-scene with his hammer at rest, the artist unmatched.",
    keyMyths: [
      'Cast from Olympus, he fell for a whole day and was taken in on Lemnos.',
      'He returned to Olympus riding a donkey, led by Dionysus, and released Hera from his trick throne.',
      'He forged the shield and armor of Achilles at Thetis\'s plea.',
      'He trapped Aphrodite and Ares in an invisible net, exposing their affair.',
      'At Zeus\'s command he fashioned Pandora, the first woman, and her fateful jar.',
    ],
    relatedIds: ['hera', 'zeus', 'aphrodite', 'ares', 'dionysus', 'achilles', 'iliad'],
    locationIds: ['lemnos', 'olympus'],
    features: [
      {
        eyebrow: 'The Smith Who Won the Fairest',
        title: 'Hephaestus and Aphrodite',
        lede: 'Cast out of heaven as a child, the lame smith took his revenge with a gift no one could resist: a golden throne that would not let the queen of heaven go. The price of her freedom was the hand of the loveliest of the goddesses.',
        facts: [
          { label: 'The gift', value: 'A golden throne' },
          { label: 'The trap', value: 'Invisible, unbreakable bonds' },
          { label: 'Who tried force', value: 'Ares — driven off with fire' },
          { label: 'Who succeeded', value: 'Dionysus, with wine' },
          { label: 'His mount home', value: 'A donkey, in procession' },
          { label: 'The price', value: 'Aphrodite’s hand' },
          { label: 'Granted by', value: 'Zeus himself' },
          { label: 'Later told of', value: 'Odyssey, Book 8' },
        ],
        sections: [
          {
            heading: 'Cast Out of Heaven',
            body: "Hephaestus was lame from birth, his legs twisted beneath the finest craftsman's hands in the world. Hera, ashamed that the queen of heaven should bear a crippled son, seized him by the foot and hurled him from Olympus — or, as Hephaestus himself tells it in the Iliad, it was Zeus who threw him on the day he took his mother's side in a quarrel. Either way, he fell a whole day long and came down on the island of Lemnos, half dead, where the Sintian folk and the sea-goddesses Thetis and Eurynome took him in. In a cave beneath the sea he learned his craft, forging ornaments for his rescuers and nursing a grievance against the mother who cast him out.",
          },
          {
            heading: 'The Golden Throne',
            body: "When he was grown and his skill unmatched in the world, Hephaestus sent a gift up to Olympus: a throne of gold, dazzling with filigree, made exactly to the measure of Hera. Delighted, the queen sat down at once — and at once invisible chains whipped about her arms and waist. She could not rise, and no god could loose the bonds; they were woven with a craft only the smith himself possessed. There she hung, trapped on her shining seat, while the gods raged and pleaded and the heavens had no queen. Hephaestus, safe in his forge, let it be known that he had no mother, and asked after no one on Olympus.",
          },
          {
            heading: 'Ares Fails, Dionysus Succeeds',
            body: "First the gods sent Ares, the war-god, to drag the smith back by force. But Hephaestus met him at his workshop door with blazing torches and a shower of burning brands, and the god of war — who knows nothing of fire's disciplines — fled howling. Then Dionysus went, and he carried no weapon at all: only wine. He sat with the smith in his smoky cave, cup after cup of sweet vintage, and by the time the wineskin was empty Hephaestus was merry and pliant and willing to come. So the lame god rode up to Olympus on a donkey, reeling drunk and grinning, with Dionysus dancing beside him and satyrs capering around with pipes and drums. The vase-painters of Athens loved this scene — the Return of Hephaestus — above almost any other: heaven's order restored not by thunder but by laughter.",
          },
          {
            heading: 'The Price of Her Freedom',
            body: "Before he would touch the bonds, Hephaestus named his price: the hand of Aphrodite, laughter-loving, loveliest of the immortals. Zeus, who wanted his queen back and his halls at peace, granted it — some say it was Hera herself who consented, there on her golden prison. So the smith undid his cunning work, Hera rose free, and a wedding was celebrated on Olympus the like of which had never been seen: the ugliest of the gods, bandy-legged and soot-stained, leading the goddess of beauty herself to the bridal chamber. The Charites, the Graces, became his companions at the forge; and Homer, who tells the tale of the fall with sympathy, gives Hephaestus his dignity back in full — he walks among the gods as an equal, and none dare pity him to his face.",
          },
          {
            heading: 'The Invisible Net',
            body: "The marriage, as everyone knows, was not a happy one. Aphrodite loved Ares, and whenever Hephaestus was away at Lemnos, the war-god came to the smith's own house and bed. But the Sun sees all things, and Helius carried word to the husband. Hephaestus went to his forge in a black rage and hammered out a net of links so fine they were invisible — thinner than spider-threads, stronger than any chain — and spread it over the bedposts of his marriage bed. Then he announced a journey to Lemnos. Ares came at once; the lovers lay down together; and the net fell. It held them fast, naked and entwined, unable to stir hand or foot.",
          },
          {
            heading: 'The Laughter of the Gods',
            body: "Then Hephaestus threw open his doors and called all the gods to see: come, Zeus, and all you blessed gods everlasting, look upon a laughable thing! They came and stood around the bed, and unquenchable laughter shook them — the goddesses, out of modesty, stayed home. Apollo nudged Hermes and asked if he would bear such chains to lie by golden Aphrodite, and Hermes answered that he would take three times the chains, and all you gods looking on, and gladly. Only Poseidon kept his countenance; he begged the smith to loose the prisoners and stood surety that Ares would pay the adulterer's fine. So the net came off, and Ares fled to Thrace and Aphrodite to her sanctuary at Paphos, where the Graces bathed her and anointed her with oil. The tale is sung in the Odyssey by the blind bard Demodocus — and if it makes the gods laugh, it is a smith's laughter, earned the hard way: he was mocked for a cripple and cuckolded in his own house, yet in the end it was his craft, not their strength or beauty, that told the final word.",
          },
        ],
      },
    ],
  },
  {
    id: 'hermes',
    name: 'Hermes',
    epithet: 'the Wayfinder',
    title: 'Messenger of the Gods, God of Travel, Trade, and Thieves',
    generation: 'olympian',
    romanName: 'Mercury',
    domain: ['travel', 'heralds and messages', 'trade', 'thieves', 'boundaries', 'guiding the dead'],
    symbols: ['caduceus', 'winged sandals', 'traveler\'s hat (petasos)', 'tortoise-shell lyre'],
    parents: 'Zeus and the nymph Maia',
    children: 'Pan',
    summary:
      "Hermes, son of Zeus and Maia, was born at dawn, invented the lyre by noon, and stole Apollo's cattle before nightfall — the most precocious trickster on Olympus. Zeus made him herald of the gods, and he moves between heaven, earth, and the underworld more freely than any other. He guides souls of the dead to the river of Hades, and so bears the title Psychopompos. He aids heroes in need: he armed Perseus, warned Odysseus against Circe, and led Priam through the sleeping Greek camp to ransom Hector's body. Witty, liminal, and kindly, he is the god of all who cross boundaries — travelers, merchants, and thieves.",
    keyMyths: [
      'On his first day of life he invented the lyre and stole Apollo\'s cattle, then talked his way out of judgment.',
      'He slew hundred-eyed Argos with song and sword to free the maiden Io.',
      'He guided the souls of the slain suitors down to the underworld at the Odyssey\'s close.',
      'He gave Odysseus the herb moly to resist Circe\'s magic.',
      'He escorted old Priam unseen into Achilles\' tent to ransom Hector\'s body.',
    ],
    relatedIds: ['zeus', 'apollo', 'perseus', 'odysseus', 'odyssey', 'iliad', 'trojan-war'],
    locationIds: ['olympus'],
  },
  {
    id: 'dionysus',
    name: 'Dionysus',
    epithet: 'the Twice-Born',
    title: 'God of Wine, Ecstasy, and the Theater',
    generation: 'olympian',
    romanName: 'Bacchus',
    domain: ['wine', 'ecstasy', 'madness', 'theater', 'vegetation'],
    symbols: ['thyrsus (pine-tipped staff)', 'grapevine', 'ivy', 'leopard', 'drinking cup (kantharos)'],
    parents: 'Zeus and the mortal Semele',
    consort: 'Ariadne',
    children: 'None of note in the mainstream myths',
    summary:
      "Dionysus is the twice-born god: Semele, blasted by the sight of Zeus in his glory, died pregnant, and Zeus sewed the infant into his own thigh until the second birth. Raised in hiding from Hera's rage, he wandered through Asia teaching the vine and gathering his retinue of Maenads and Satyrs. His worship is ecstasy — wine, dance, and the loosening of the self — and his theater at Athens gave birth to tragedy itself. He is gentle to those who receive him and merciless to those who refuse: King Pentheus of Thebes, who denied his divinity, was torn apart by his own mother in the god's frenzy. Youngest of the Olympians, he took in some traditions the seat that Hestia yielded.",
    keyMyths: [
      'Born from the thigh of Zeus after Semele was consumed by his lightning.',
      'In Euripides\' Bacchae he returned to Thebes and destroyed King Pentheus, who spurned his rites.',
      'Pirates who kidnapped him were turned into dolphins when vines engulfed their ship.',
      'He found Ariadne abandoned by Theseus on Naxos and made her his immortal bride.',
      'He descended to the underworld and led his mother Semele up to Olympus.',
    ],
    relatedIds: ['zeus', 'hera', 'hestia', 'theseus', 'hephaestus', 'house-of-cadmus', 'house-of-thebes'],
    locationIds: ['olympus', 'thebes', 'naxos'],
  },
];

export const otherDeities: God[] = [
  {
    id: 'hestia',
    name: 'Hestia',
    epithet: 'Keeper of the Hearth',
    title: 'Goddess of the Hearth, Home, and Sacred Fire',
    generation: 'olympian',
    romanName: 'Vesta',
    domain: ['the hearth', 'home', 'domestic and civic fire'],
    symbols: ['hearth fire', 'kettle', 'veil'],
    parents: 'Cronus and Rhea',
    children: 'None — she is an eternal maiden',
    summary:
      "Hestia, eldest daughter of Cronus and Rhea, was the first swallowed by her father and the last disgorged — both oldest and youngest of his children. Wooed by Poseidon and Apollo, she refused both and swore by Zeus's head to remain a maiden forever, receiving in return the central seat of every household and temple. Every Greek sacrifice began and ended with an offering to her, and every city's public hearth held her undying flame. She has almost no myths of her own, for she never leaves home; her power is presence itself. In some traditions she was counted among the Twelve Olympians, later yielding her seat to Dionysus.",
    keyMyths: [
      'First swallowed and last released by Cronus, she is both the eldest and youngest of his children.',
      'She rejected the suits of Poseidon and Apollo and swore eternal maidenhood.',
      'Every sacrifice in Greece opened and closed with an offering to Hestia.',
      'She yielded her seat among the Twelve to Dionysus rather than see the gods quarrel.',
    ],
    relatedIds: ['cronus', 'rhea', 'zeus', 'poseidon', 'apollo', 'dionysus', 'demeter', 'hera'],
    locationIds: ['olympus'],
  },
  {
    id: 'hades',
    name: 'Hades',
    epithet: 'the Unseen One',
    title: 'God of the Underworld and the Dead',
    generation: 'olympian',
    romanName: 'Pluto',
    domain: ['the underworld', 'the dead', 'hidden wealth of the earth'],
    symbols: ['bident', 'helm of invisibility', 'Cerberus', 'cypress', 'keys'],
    parents: 'Cronus and Rhea',
    consort: 'Persephone',
    children: 'None in mainstream myth',
    summary:
      "Hades, brother of Zeus and Poseidon, drew the underworld as his lot and rules there over the shades of all the dead. He is not Death itself — that is Thanatos — but the host who receives everyone, and so the poets call him the Receiver of Many. He rarely leaves his realm and takes no part in the quarrels of Olympus; even his one great passion, the abduction of Persephone, was sanctioned by Zeus. Mortals feared to speak his name and called him Plouton, the Wealth-Giver, for the riches of grain and ore that rise from below. His three-headed hound Cerberus guards the gates so that none who enter may return.",
    keyMyths: [
      'He drew the underworld by lot when the three brothers divided the cosmos.',
      'With Zeus\'s consent he seized Persephone and made her queen of the dead.',
      'He lent Perseus the helm of invisibility used to slay Medusa.',
      'Heracles wrestled Cerberus from his gates as the final Labor.',
      'He allowed Orpheus to lead Eurydice back — on a condition Orpheus failed to keep.',
    ],
    relatedIds: ['zeus', 'poseidon', 'persephone', 'demeter', 'cronus', 'rhea', 'heracles', 'orpheus', 'perseus'],
    locationIds: ['underworld'],
  },
  {
    id: 'persephone',
    name: 'Persephone',
    epithet: 'the Iron Queen',
    title: 'Queen of the Underworld, Goddess of Spring',
    generation: 'olympian',
    romanName: 'Proserpina',
    domain: ['spring', 'vegetation', 'the underworld'],
    symbols: ['pomegranate', 'torch', 'sheaf of grain', 'flowers'],
    parents: 'Zeus and Demeter',
    consort: 'Hades',
    children: 'None in mainstream myth',
    summary:
      "Persephone, called Kore, 'the Maiden,' is the daughter of Demeter and Zeus. Hades seized her as she gathered flowers and carried her below to be his queen, and her mother's grief turned the earth barren until a compromise was struck. Because she had eaten seeds of the pomegranate in the underworld, she must spend a portion of each year below, returning each spring as the world blooms. She is thus two goddesses in one: the bright maiden of the meadow and the dread queen enthroned beside Hades, whom even heroes address with care. To the initiates of Eleusis she was the promise that death is not the end.",
    keyMyths: [
      'Hades burst from the earth in his chariot and seized her as she gathered flowers.',
      'She ate pomegranate seeds in the underworld, binding her to return each year.',
      'Her annual descent and return explain the turning of the seasons.',
      'As queen of the dead she heard Orpheus\'s plea and judged Admetus\'s and Alcestis\'s fates.',
    ],
    relatedIds: ['demeter', 'hades', 'zeus', 'orpheus', 'heracles'],
    locationIds: ['underworld', 'olympus'],
  },
  {
    id: 'hebe',
    name: 'Hebe',
    epithet: 'Cupbearer of the Gods',
    title: 'Goddess of Youth',
    generation: 'olympian',
    domain: ['youth', 'the prime of life'],
    symbols: ['cup', 'pitcher of nectar', 'wings'],
    parents: 'Zeus and Hera',
    consort: 'Heracles (after his apotheosis)',
    children: 'None of note',
    summary:
      "Hebe, daughter of Zeus and Hera, is the divine image of youth in its bloom. She served nectar and ambrosia to the gods at their feasts, a duty later given to the Trojan prince Ganymede. When Heracles was raised to Olympus after his fiery death, Zeus gave him Hebe as wife — the peace that crowned the hero's long suffering, and with it reconciliation with Hera at last. She also attended her mother, preparing her chariot and her bath. Though few myths gather around her, she was honored alongside Heracles in his cults as the grace of undying youth.",
    keyMyths: [
      'She poured nectar for the gods until Ganymede was brought to Olympus.',
      'She wed the deified Heracles, sealing his reconciliation with Hera.',
      'She attended Hera, harnessing her chariot and drawing her bath.',
    ],
    relatedIds: ['zeus', 'hera', 'heracles', 'ares'],
    locationIds: ['olympus'],
  },
  {
    id: 'eris',
    name: 'Eris',
    epithet: 'Lady of Discord',
    title: 'Goddess of Strife and Discord',
    generation: 'olympian',
    domain: ['strife', 'discord', 'rivalry'],
    symbols: ['golden apple'],
    parents: 'Nyx alone (Hesiod); Homer calls her sister of Ares',
    children: 'Toil, Famine, Lies, Battles, and the other Strifes (Hesiod)',
    summary:
      "Eris is strife personified, daughter of Night and, in Homer, the sister and companion of Ares who grows as battle grows. Hesiod distinguishes two kinds: the hateful strife that breeds war, and the good strife that spurs men to rival one another in work. Her single most famous act shaped all of heroic legend: uninvited to the wedding of Peleus and Thetis, she threw among the goddesses a golden apple inscribed 'for the fairest.' The quarrel of Hera, Athena, and Aphrodite that followed led to the Judgment of Paris — and so to the Trojan War. Small at first, the poets say, she plants her head in heaven while her feet walk the earth.",
    keyMyths: [
      'She threw the golden apple at the wedding of Peleus and Thetis, sparking the chain of the Trojan War.',
      'Hesiod makes her the daughter of Nyx and mother of every hardship that plagues mankind.',
      'In the Iliad she walks beside Ares, small at first, then towering to the sky.',
      'Hesiod also praises a second, beneficial Strife that drives craftsmen to compete and excel.',
    ],
    relatedIds: ['nyx', 'ares', 'aphrodite', 'athena', 'hera', 'trojan-war'],
    locationIds: ['olympus', 'troy'],
  },
  {
    id: 'nike',
    name: 'Nike',
    epithet: 'the Winged Victory',
    title: 'Goddess of Victory',
    generation: 'olympian',
    romanName: 'Victoria',
    domain: ['victory in war and contest'],
    symbols: ['wings', 'laurel wreath', 'palm branch'],
    parents: 'The Titan Pallas and the river-goddess Styx',
    summary:
      "Nike, daughter of the Titan Pallas and Styx, is victory given wings. When Zeus summoned the gods to war against the Titans, Styx brought her children — Victory, Force, and Might — to his side, and Zeus honored them by keeping them forever near his throne. Nike appears in myth less as an actor than as a presence: she flies to the victor's shoulder, crowns the athlete, and steadies the spear-throw of Athena, with whom she shared a temple on the Athenian Acropolis. Winged, garlanded, and swift, she became one of the most beloved images of Greek art.",
    keyMyths: [
      'She came with her mother Styx to Zeus\'s side before the Titanomachy and never left his court.',
      'She crowns victors in war, athletics, and song with wreath and palm.',
      'On the Athenian Acropolis she was worshiped beside Athena as Athena Nike.',
    ],
    relatedIds: ['zeus', 'athena', 'cronus'],
    locationIds: ['olympus', 'athens'],
  },
];
